# SPDX-License-Identifier: Apache-2.0
"""散落在 bootstrap / seed 子模块中的中文 → 英文对照（SEED_LOCALE=en 时 seed_text 使用）。

算法码（弱/中/强/爆 等作为字典键）不要放进本表。
"""

from __future__ import annotations

EN_STRINGS: dict[str, str] = {
    # Roles / users
    "系统管理员": "System Admin",
    "店长": "General Manager",
    "收益经理": "Revenue Manager",
    "前台": "Front Desk",
    "客房": "Housekeeping",
    "保洁": "Housekeeping",
    "工程": "Engineering",
    "全权限": "Full access",
    "单店经营": "Property ops",
    "定价收益": "Pricing & revenue",
    "接待收银": "Reception & cashier",
    # Amenities / tags already in pack but used inline
    "含早": "Breakfast",
    "可加床": "Extra bed OK",
    "会客厅": "Living area",
    "浴缸": "Bathtub",
    "淋浴": "Shower",
    "默认收益护栏": "Default revenue guardrail",
    # Cities
    "北京": "Beijing",
    "上海": "Shanghai",
    "广州": "Guangzhou",
    "深圳": "Shenzhen",
    "杭州": "Hangzhou",
    "本地": "Local",
    "房满乐": "fangmanle",
    "请在本店设置中填写地址": "Set address in property settings",
    # HK staff
    "王阿姨": "Auntie Wang",
    "李姐": "Sister Li",
    "张师傅": "Master Zhang",
    "赵保洁": "Zhao (HK)",
    "陈大姐": "Chen (HK)",
    "李工": "Engineer Li",
    "王工": "Engineer Wang",
    "丁祥外机": "Ding (outdoor unit)",
    # Pricing events
    "中秋节": "Mid-Autumn Festival",
    "国庆黄金周": "National Day Golden Week",
    "周杰伦上海演唱会": "Jay Chou Shanghai Concert",
    "酒店用品展": "Hotel Supplies Expo",
    # Mkt campaigns (ensure_mkt)
    "国庆连住7折": "National Day Stay 30% Off",
    "周末早鸟价": "Weekend Early Bird",
    # Owned audience — coupons / landing / levels / points
    "企微好友专享 · 房费7折券": "WeCom friends · 30% off room",
    "满减券 · 满300减50": "Spend ¥300 save ¥50",
    "连住送夜券": "Stay-N-get-1 night voucher",
    "无门槛通用立减¥50": "¥50 off · no minimum",
    "注册满30天 · 立减¥10": "30-day member · ¥10 off",
    "注册满100天 · 立减¥20": "100-day member · ¥20 off",
    "退房后复购 · 满300减80": "7 days post-stay · ¥80 off ¥300+",
    "新客欢迎礼 · 房价7折": "New guest welcome · 30% off room",
    "退房后7天 · 满减券": "7 days post-stay voucher",
    "企微扫码领券": "WeCom scan to claim",
    "企微会员中心": "WeCom member center",
    "老客回访": "Returning guest welcome",
    "银卡": "Silver",
    "金卡": "Gold",
    "白金卡": "Platinum",
    "钻石卡": "Diamond",
    "至尊卡": "Supreme",
    "积分仅限本店企微 H5 私域使用，与 PMS 全局会员积分无关。": "Points for this property's WeCom H5 owned audience only; not global PMS member points.",
    "积分全渠道累计；使用范围可配置为前台 / 前台+企微H5 / 全渠道。": "Points accrue all channels; redeem at front desk / front+WeCom H5 / all channels.",
    "指定房型立减¥{amt}（满{thr}可用）": "¥{amt} off selected room types (min ¥{thr})",
    "指定房型立减¥{amt}": "¥{amt} off selected room types",
    "通用立减¥{amt}（无门槛）": "¥{amt} off all (no minimum)",
    "{n}折": "{n}% off",
    "房价{label}（最高减¥{cap}）": "Room {label} (max ¥{cap} off)",
    "房价{label}": "Room {label}",
    "专属管家 · 扫码礼遇": "Dedicated host · scan gift",
    "填写手机号 领取优惠券": "Enter mobile to claim coupon",
    "提交后开通专属管家档案，优惠券可在本店房费使用。": "Submit to open your host profile; coupon applies to room charges here.",
    "手机号": "Mobile",
    "请输入预订/入住手机号": "Booking/stay mobile number",
    "提交并领取优惠券": "Submit & claim coupon",
    "提交后将绑定专属管家档案（OneID）。每份企微身份仅可领取一次。优惠券仅限本店房费使用。": "Submit binds your OneID host profile. One claim per WeCom identity. Room charges at this property only.",
    "专属会员中心": "Member center",
    "我的会员中心": "My member center",
    "查看私域优惠券、订单与会员权益": "View owned-audience coupons, orders & benefits",
    "我的券": "My coupons",
    "历史订单": "Order history",
    "权益中心": "Benefits",
    "私域优惠券": "Owned-audience coupons",
    "本页由酒店装修发布。券仅限本店私域渠道发放，到店出示券码即可核销。": "Published by the hotel. Coupons via owned channels only; redeem in store with code.",
    "欢迎回来": "Welcome back",
    "{guest_name}，您的私域礼遇": "{guest_name}, your owned-audience perks",
    "欢迎回来！以下是您在本店私域领取的全部优惠券": "Welcome back! All coupons you claimed via owned audience at this hotel.",
    "进入专属会员中心": "Open member center",
    # Landing system templates (WxLandingTemplate.name + inline blocks)
    "会员中心": "Member center",
    "单券领取（企微欢迎语）": "Single coupon (WeCom welcome)",
    "老客回访（券包）": "Returning guest (coupon pack)",
    "券包大礼包": "Coupon gift pack",
    "节日活动页": "Festival campaign page",
    "会员专享领券": "Member-exclusive coupon",
    "新人礼包到账": "New guest pack ready",
    "领完即可预订": "Claim then book",
    "限时": "Limited time",
    "11 位手机号": "11-digit mobile",
    "一键领取": "Claim all",
    "中秋连住特惠": "Mid-Autumn multi-night deal",
    "连住两晚更划算": "Two nights — better value",
    "中秋": "Mid-Autumn",
    "节日主视觉": "Festival hero image",
    "立即领取": "Claim now",
    "会员专享折扣": "Member-only discount",
    "登录手机号核销身份": "Verify with mobile",
    "会员": "Member",
    "会员手机号": "Member mobile",
    "领取会员券": "Claim member coupon",
    "联系专属管家": "Contact your host",
    # Room types (if leftover CN)
    "经济标间": "Economy Twin",
    "豪华大床房": "Deluxe King",
    "尊享大床房": "Premier King",
    "商务双床房": "Business Twin",
    "家庭亲子房": "Family Room",
    "行政套房": "Executive Suite",
    "双床": "Twin",
    "大床": "King",
    "一大一小": "King + Single",
    # Channels
    "携程": "Ctrip",
    "美团酒店": "Meituan Hotel",
    "美团": "Meituan",
    "飞猪": "Fliggy",
    "抖音团购": "Douyin Deals",
    "抖音来客": "Douyin Life",
    "美团团购": "Meituan Voucher",
    "小红书": "Xiaohongshu",
    "散客直订": "Walk-in / Direct",
    "百度地图": "Baidu Maps",
    "高德地图": "Amap",
    "常住客": "Long-stay",
    "协议客户": "Corporate",
    "企微私域": "WeCom Owned Audience",
    "官网直订": "Official direct",
    "同程/去哪儿": "Tongcheng / Qunar",
    "艺龙": "eLong",
    "京东": "JD",
    # Guest tags
    "高价值客户": "High-value guest",
    "价格敏感": "Price sensitive",
    "亲子家庭": "Family with kids",
    "商务常旅客": "Business frequent",
    "投诉风险": "Complaint risk",
    "抖音粉丝": "Douyin fan",
    "小红书种草": "Xiaohongshu fan",
    "复购客": "Repeat guest",
    "偏好高层安静房": "Prefers quiet high floor",
    "近90天活跃": "Active in last 90 days",
    "IoT异常信号": "IoT anomaly signal",
    # Supplies
    "易耗品": "Consumables",
    "布草": "Linen",
    "清洁用品": "Cleaning",
    "客用品": "Guest amenities",
    "牙具套装": "Dental kit",
    "洗发水": "Shampoo",
    "拖鞋": "Slippers",
    "床单": "Bed sheet",
    "浴巾": "Bath towel",
    "吸尘袋": "Vacuum bag",
    "矿泉水": "Mineral water",
    "茶包": "Tea bag",
    # Assets / maintenance
    "预防性保养": "Preventive maintenance",
    "紧急检修": "Emergency repair",
    "定期保养": "Scheduled maintenance",
    "历史维修": "Historical repair",
    "季度例行": "Quarterly routine",
    "已归档维修": "Archived repair",
    "维保": "Maintenance",
    "维保工单": "Maintenance WO",
    "设备": "Equipment",
    "待指派": "Unassigned",
    "暖通": "HVAC",
    "空调暖通": "HVAC",
    "客房设备": "In-room",
    "弱电": "Low-voltage",
    "公区": "Public area",
    "电梯": "Elevator",
    "门禁安防": "Access & security",
    "门锁安防": "Access & security",
    "卫浴设备": "Bathroom fixtures",
    "大金中央空调": "Daikin central AC",
    "大金空调维保成本偏高": "Daikin AC maintenance cost is high",
    "累计维保已接近原值 35%，建议评估 6 个月内整机置换。": "Cumulative repairs near 35% of original cost — evaluate full replacement within 6 months.",
    "累计维修已接近原值 35%，建议评估 6 个月内整机置换。": "Cumulative repairs near 35% of original cost — evaluate full replacement within 6 months.",
    "黄灯资产集中维保": "Yellow-status assets — batch maintenance",
    "建议明日 11:00-14:00 低入住时段统一安排预防性维护，可自动生成工单。": "Schedule preventive maintenance tomorrow 11:00–14:00 (low occupancy); WOs can be auto-created.",
    "丝涟床垫临近更换周期": "Sealy mattress near replacement",
    "302 房床垫基于高入住率外推，约 2 个月后进入最佳更换末端。": "Room 302 mattress (high occupancy) — best replace window in ~2 months.",
    "弱电门锁电量集群风险": "Cluster risk: lock batteries low",
    "5F 多把门锁电量告警，建议批量更换电池避免夜间开锁失败。": "Multiple 5F locks low battery — batch replace to avoid night failures.",
    "固定物品盘点差异待核": "Fixed-item inventory variance",
    "遥控器/吹风机等差异已入盘点表，请工程与房务联合复核。": "Remote/dryer variances on audit sheet — eng + HK to verify.",
    "入库采购": "Purchase inbound",
    "初次安装": "Initial install",
    "历次维保/维修": "Past maintenance / repair",
    "AI 故障预测点": "AI failure prediction",
    "采购部": "Purchasing",
    "工程部": "Engineering",
    "花洒水压与密封例行检查": "Shower pressure & seal routine check",
    "滤网与排水需季节性保养": "Filter & drain seasonal service",
    # HK tips
    "高优：临近预抵或 VIP，建议优先闭环。": "High priority: near arrival or VIP — close first.",
    "退房空脏，建议按楼层就近派工。": "Checkout dirty — assign nearby by floor.",
    "清洁已完成，待查房验收后才可改空净。": "Cleaning done — vacant-clean only after inspection.",
    # Misc seed prints / labels
    "数据已存在，跳过主种子（使用 --reset 重建）。": "Data exists; skip core seed (use --reset to rebuild).",
    "设备设施种子已写入（台账/告警/洞察/事件/盘点/维保）。": "Assets seed written (ledger/alerts/insights/events/audit/maint).",
    "未分房型": "Unassigned type",
    "工程外包": "Outsourced eng",
    "供应商": "Supplier",
    "安装于": "Installed at",
    "维修归档": "Repair archived",
    "建议生成预防性工单": "Suggest preventive WO",
    "索尼 65寸 智能电视": 'Sony 65" smart TV',
    "智能门锁": "Smart door lock",
    "大堂香氛机": "Lobby aroma unit",
    "客梯 A": "Elevator A",
    "丝涟床垫": "Sealy mattress",
    "待机功耗略升，建议纳入下周巡检": "Standby power slightly up — include in next week's round",
    "运行功率偏高 20%，建议清洗滤网": "Running power +20% — clean filters",
    "剩余电量低于 15%，预计可维持 3 天": "Battery below 15% — ~3 days left",
    "水压异常波动，建议立即检查水阀": "Water pressure swing — check valve now",
    "香氛溶液预计明晚耗尽": "Aroma solution runs out tomorrow night",
    "本周例行检修窗口，请预留停梯时段": "Routine service window this week — reserve elevator downtime",
    "1F大堂": "1F Lobby",
    "大堂": "Lobby",
    # Deposit ledger memos / guest fallbacks
    "收押": "Collect",
    "扣减": "Capture",
    "预授权过期": "Pre-auth expired",
    "金额不符": "Amount mismatch",
    "今日退还": "Refunded today",
    "迷你吧扣减": "Minibar capture",
    "金额不符争议": "Amount dispute",
    "张女士": "Ms. Zhang",
    "王女士": "Ms. Wang",
    "刘先生": "Mr. Liu",
    "孙先生": "Mr. Sun",
    "蒋阿姨": "Auntie Jiang",
    "协议客": "Corp guest",
    "已退客人": "Refunded guest",
    # Refund / reverse tickets
    "部分退款 · No.8821": "Partial refund · No.8821",
    "反结账 · 房 1108": "Folio reverse · Room 1108",
    "取消 1 晚，退 ¥428": "Cancel 1 night, refund ¥428",
    "房费算错，重开账单": "Room charge error — reopen folio",
    "房费算错": "Room charge error",
    "客人要求取消第 2 晚": "Guest asked to cancel night 2",
    "冲正 · 协议挂账早餐": "Adjustment · corp breakfast",
    "误收早餐 ¥76": "Breakfast charged in error ¥76",
    "误收早餐费": "Breakfast charged in error",
    "系统初始化工单": "System seed ticket",
    "待办退款 · 点入可定位源单": "Pending refund · open to locate source order",
    "退款待办工单": "Refund pending ticket",
    # Finance params / OTA commission
    "一般纳税人": "General VAT taxpayer",
    "价外": "Tax-exclusive",
    "价内": "Tax-inclusive",
    "城建 7% / 教育 3% / 地方教育 2%": "Urban const. 7% / Education 3% / Local education 2%",
    "一般纳税人核定": "General taxpayer approval",
    "主营税率": "Main tax rate",
    "税率": "Tax rate",
    "已生效": "Effective",
    "系统初始化": "System init",
    "门店开业初始化": "Property go-live init",
    "初始化税率 6% + 8 类客户账期": "Init 6% tax + 8 customer terms",
    "财务-周敏": "Finance · Zhou Min",
    "店长-李建国": "GM · Li Jianguo",
    "财务-周敏 / 店长-李建国": "Finance · Zhou Min / GM · Li Jianguo",
    "月结": "Monthly",
    "实时": "Realtime",
    "老板/财务": "Owner / Finance",
    "整改后 10/12/15% 自选，本表存中档 12%": "Post-reform 10/12/15% tiers; mid 12% stored here",
    "舒适型及以上 10% 起": "Comfort tier and above from 10%",
    "阿里系导流，行业最低区间": "Alibaba traffic; low end of market range",
    "2025-01 起核销佣金 8%": "8% redemption commission from Jan 2025",
    "携程系，12%–18%": "Ctrip group, 12%–18%",
    "携程系，分销 10%–15%": "Ctrip group distribution, 10%–15%",
    "三年期零佣金（流量待验证）": "3-year zero commission (traffic TBD)",
    "仅支付通道 ~1.5%，房满乐战略重心": "Payment rails ~1.5%; fangmanle strategic focus",
    "仅支付通道 ~2%，私域直订": "Payment rails ~2%; private-domain direct",
    "海外渠道，跨境客参考": "Overseas channel; cross-border reference",
    "小程序/会员": "Mini-program / Member",
    "散客": "Walk-in",
    "会员预付": "Member prepaid",
    "OTA 携程": "OTA Ctrip",
    "OTA 美团": "OTA Meituan",
    "OTA 飞猪": "OTA Fliggy",
    "OTA 抖音来客": "OTA Douyin Life",
    "企业挂账": "Corporate AR",
    "旅行社": "Travel agency",
    "即付 · 0 天": "Pay-at-checkout · 0 days",
    "现结 · 0 天": "Settled · 0 days",
    "结账离店时现金/扫码/刷卡，0 账期": "Cash/QR/card at checkout; 0 terms",
    "已收款，作为预收负债入账": "Collected; booked as deferred revenue",
    "携程代收代付，平台 15 日结款": "Ctrip collect & pay; T+15 settlement",
    "美团代收代付": "Meituan collect & pay",
    "飞猪代收代付": "Fliggy collect & pay",
    "抖音代收代付": "Douyin collect & pay",
    "协议单位挂账，需在信用与账龄中维护额度": "Corporate AR; maintain limit under Credit & aging",
    "地接社挂账，账期较短": "Local agency AR; shorter terms",
    "微信支付": "WeChat Pay",
    "支付宝": "Alipay",
    "银联二维码": "UnionPay QR",
    "银行卡 POS（借记卡）": "Card POS (debit)",
    "银行卡 POS（贷记卡）": "Card POS (credit)",
    "云闪付": "UnionPay NFC",
    "上线": "Live",
    "低用量": "Low volume",
    "未启用": "Disabled",
    "中青旅控股": "CYTS Holdings",
    "某商务旅行社": "Sample business agency",
    "本地科技公司": "Local tech company",
    "携程商旅": "Ctrip Business Travel",
    "美团商旅": "Meituan Business Travel",
    "飞猪商旅": "Fliggy Business Travel",
    "某小旅行社": "Sample small agency",
    "某问题客户": "Sample problem account",
    "超额预警": "Over-limit alert",
    "降级观察": "Downgrade watch",
    "停用挂账": "AR suspended",
    "15 天": "15 days",
    "30 天": "30 days",
    "0–30 天": "0–30 days",
    "30–60 天": "30–60 days",
    "60–90 天": "60–90 days",
    "90+ 天": "90+ days",
    "正常账期，不计提": "Current; no provision",
    "轻度逾期风险": "Mild overdue risk",
    "明显逾期": "Materially overdue",
    "高风险，需总经理核销": "High risk; GM write-off required",
    "正常": "Normal",
}
