-- SPDX-License-Identifier: Apache-2.0
-- 演示数据兼容：去掉过严 CHECK；为 core 表补运行时单租户 schema 多出来的列（兼容演示数据）
ALTER TABLE channels DROP CONSTRAINT IF EXISTS channels_type_check;
ALTER TABLE guests DROP CONSTRAINT IF EXISTS guests_gender_check;
ALTER TABLE guests DROP CONSTRAINT IF EXISTS guests_vip_level_check;
ALTER TABLE orders DROP CONSTRAINT IF EXISTS orders_status_check;
ALTER TABLE orders DROP CONSTRAINT IF EXISTS orders_payment_status_check;
ALTER TABLE rooms DROP CONSTRAINT IF EXISTS rooms_status_check;
ALTER TABLE risk_alerts DROP CONSTRAINT IF EXISTS risk_alerts_level_check;
ALTER TABLE risk_alerts DROP CONSTRAINT IF EXISTS risk_alerts_status_check;
ALTER TABLE campaigns DROP CONSTRAINT IF EXISTS campaigns_channel_check;
ALTER TABLE guest_identities DROP CONSTRAINT IF EXISTS guest_identities_source_check;
ALTER TABLE venue_bookings DROP CONSTRAINT IF EXISTS venue_bookings_status_check;
-- assets 的 status 白名单不含 abnormal（演示库含一台水压异常设备，真实故障态），放松以容纳演示数据
ALTER TABLE assets DROP CONSTRAINT IF EXISTS assets_status_check;

ALTER TABLE asset_maintenance ADD COLUMN IF NOT EXISTS note VARCHAR(200);
ALTER TABLE asset_maintenance ADD COLUMN IF NOT EXISTS owner VARCHAR(40);
ALTER TABLE asset_maintenance ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ;
ALTER TABLE assets ADD COLUMN IF NOT EXISTS asset_no VARCHAR(40);
ALTER TABLE assets ADD COLUMN IF NOT EXISTS room_no VARCHAR(20);
ALTER TABLE assets ADD COLUMN IF NOT EXISTS sn VARCHAR(60);
ALTER TABLE assets ADD COLUMN IF NOT EXISTS brand_model VARCHAR(80);
ALTER TABLE assets ADD COLUMN IF NOT EXISTS repair_cost_total NUMERIC(12, 2);
ALTER TABLE assets ADD COLUMN IF NOT EXISTS health_score INTEGER;
ALTER TABLE assets ADD COLUMN IF NOT EXISTS insight VARCHAR(200);
ALTER TABLE assets ADD COLUMN IF NOT EXISTS warranty_until DATE;
ALTER TABLE assets ADD COLUMN IF NOT EXISTS runtime_hours INTEGER;
ALTER TABLE assets ADD COLUMN IF NOT EXISTS avg_power_w NUMERIC(10, 2);
ALTER TABLE assets ADD COLUMN IF NOT EXISTS next_maintain_date DATE;
ALTER TABLE assets ADD COLUMN IF NOT EXISTS supplier VARCHAR(80);
ALTER TABLE assets ADD COLUMN IF NOT EXISTS dept VARCHAR(40);
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS external_plan_id VARCHAR(80);
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS status VARCHAR(20);
ALTER TABLE channels ADD COLUMN IF NOT EXISTS settle_cycle VARCHAR(16);
ALTER TABLE channels ADD COLUMN IF NOT EXISTS note VARCHAR(255);
ALTER TABLE channels ADD COLUMN IF NOT EXISTS owner_role VARCHAR(32);
ALTER TABLE channels ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE channels ADD COLUMN IF NOT EXISTS updated_by VARCHAR(32);
ALTER TABLE guest_identities ADD COLUMN IF NOT EXISTS is_primary BOOLEAN;
ALTER TABLE guest_identities ADD COLUMN IF NOT EXISTS merge_method VARCHAR(30);
ALTER TABLE guest_identities ADD COLUMN IF NOT EXISTS matched_by VARCHAR(60);
ALTER TABLE guests ADD COLUMN IF NOT EXISTS merged_into_guest_id INTEGER;
ALTER TABLE guests ADD COLUMN IF NOT EXISTS phone_cipher TEXT;
ALTER TABLE guests ADD COLUMN IF NOT EXISTS phone_mask VARCHAR(20);
ALTER TABLE guests ADD COLUMN IF NOT EXISTS phone_hash VARCHAR(64);
ALTER TABLE housekeeping_tasks ADD COLUMN IF NOT EXISTS inspect_by INTEGER;
ALTER TABLE housekeeping_tasks ADD COLUMN IF NOT EXISTS inspect_at TIMESTAMPTZ;
ALTER TABLE housekeeping_tasks ADD COLUMN IF NOT EXISTS fail_reason VARCHAR(200);
ALTER TABLE housekeeping_tasks ADD COLUMN IF NOT EXISTS fail_count SMALLINT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS arrival_time VARCHAR(5);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS external_order_no VARCHAR(80);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS voucher_code VARCHAR(80);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS group_name VARCHAR(120);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS group_type VARCHAR(40);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS settle_mode VARCHAR(40);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS settle_party VARCHAR(120);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS sales_name VARCHAR(80);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS other_amount NUMERIC(12,2);
ALTER TABLE room_types ADD COLUMN IF NOT EXISTS area INTEGER;
ALTER TABLE room_types ADD COLUMN IF NOT EXISTS amenities TEXT;
ALTER TABLE room_types ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE room_types ADD COLUMN IF NOT EXISTS image_url VARCHAR(500);
ALTER TABLE room_types ADD COLUMN IF NOT EXISTS has_window BOOLEAN;
ALTER TABLE room_types ADD COLUMN IF NOT EXISTS orientation VARCHAR(40);
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS status_note VARCHAR(200);
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS status_until DATE;
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS smoking BOOLEAN;
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS features VARCHAR(200);
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS lock_id VARCHAR(60);
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS physical_status VARCHAR(20);
ALTER TABLE staff_shifts ADD COLUMN IF NOT EXISTS source VARCHAR(20);
-- demo 含 CHECK 白名单外的值 ['doing']，放松 asset_maintenance_status_check
ALTER TABLE asset_maintenance DROP CONSTRAINT IF EXISTS asset_maintenance_status_check;
-- demo 含 CHECK 白名单外的值 ['abnormal']，放松 assets_status_check
ALTER TABLE assets DROP CONSTRAINT IF EXISTS assets_status_check;
-- demo 含 CHECK 白名单外的值 ['booking', 'geo', 'longstay', 'map', 'membership', 'voucher']，放松 channels_type_check
ALTER TABLE channels DROP CONSTRAINT IF EXISTS channels_type_check;
-- demo 含 CHECK 白名单外的值 ['ctrip', 'fliggy', 'meituan', 'wecom']，放松 guest_identities_source_check
ALTER TABLE guest_identities DROP CONSTRAINT IF EXISTS guest_identities_source_check;
-- demo 含 CHECK 白名单外的值 ['女', '男']，放松 guests_gender_check
ALTER TABLE guests DROP CONSTRAINT IF EXISTS guests_gender_check;
-- demo 含 CHECK 白名单外的值 ['other']，放松 order_items_item_type_check
ALTER TABLE order_items DROP CONSTRAINT IF EXISTS order_items_item_type_check;
-- demo 含 CHECK 白名单外的值 ['confirmed', 'reserved']，放松 orders_status_check
ALTER TABLE orders DROP CONSTRAINT IF EXISTS orders_status_check;
-- demo 含 CHECK 白名单外的值 ['on_account']，放松 orders_payment_status_check
ALTER TABLE orders DROP CONSTRAINT IF EXISTS orders_payment_status_check;
-- demo 含 CHECK 白名单外的值 ['alipay_pos', 'ctrip', 'deposit_offset', 'direct', 'douyin', 'fliggy', 'meituan', 'wechat_pos', 'xiaohongshu']，放松 payments_method_check
ALTER TABLE payments DROP CONSTRAINT IF EXISTS payments_method_check;
-- demo 含 CHECK 白名单外的值 ['中', '高']，放松 risk_alerts_level_check
ALTER TABLE risk_alerts DROP CONSTRAINT IF EXISTS risk_alerts_level_check;
-- demo 含 CHECK 白名单外的值 ['closed']，放松 risk_alerts_status_check
ALTER TABLE risk_alerts DROP CONSTRAINT IF EXISTS risk_alerts_status_check;
-- demo 含 CHECK 白名单外的值 ['VD']，放松 rooms_status_check
ALTER TABLE rooms DROP CONSTRAINT IF EXISTS rooms_status_check;
-- demo 含 CHECK 白名单外的值 ['off']，放松 staff_shifts_shift_check
ALTER TABLE staff_shifts DROP CONSTRAINT IF EXISTS staff_shifts_shift_check;
ALTER TABLE acquisition_contents DISABLE TRIGGER ALL;
ALTER TABLE acquisition_leads DISABLE TRIGGER ALL;
ALTER TABLE ai_action_confirmations DISABLE TRIGGER ALL;
ALTER TABLE ai_ask_queries DISABLE TRIGGER ALL;
ALTER TABLE ai_ask_sessions DISABLE TRIGGER ALL;
ALTER TABLE ai_commands DISABLE TRIGGER ALL;
ALTER TABLE ai_diagnosis_results DISABLE TRIGGER ALL;
ALTER TABLE ai_report_interpretations DISABLE TRIGGER ALL;
ALTER TABLE ap_invoices DISABLE TRIGGER ALL;
ALTER TABLE app_settings DISABLE TRIGGER ALL;
ALTER TABLE ar_ap_logs DISABLE TRIGGER ALL;
ALTER TABLE ar_invoices DISABLE TRIGGER ALL;
ALTER TABLE asset_alerts DISABLE TRIGGER ALL;
ALTER TABLE asset_audit_items DISABLE TRIGGER ALL;
ALTER TABLE asset_events DISABLE TRIGGER ALL;
ALTER TABLE asset_insights DISABLE TRIGGER ALL;
ALTER TABLE asset_maintenance DISABLE TRIGGER ALL;
ALTER TABLE assets DISABLE TRIGGER ALL;
ALTER TABLE campaigns DISABLE TRIGGER ALL;
ALTER TABLE channel_attribution DISABLE TRIGGER ALL;
ALTER TABLE channel_commission DISABLE TRIGGER ALL;
ALTER TABLE channels DISABLE TRIGGER ALL;
ALTER TABLE competitor_property DISABLE TRIGGER ALL;
ALTER TABLE competitor_rate_snapshot DISABLE TRIGGER ALL;
ALTER TABLE competitor_room_map DISABLE TRIGGER ALL;
ALTER TABLE competitor_set DISABLE TRIGGER ALL;
ALTER TABLE corp_accounts DISABLE TRIGGER ALL;
ALTER TABLE corp_price_ladders DISABLE TRIGGER ALL;
ALTER TABLE crm_tasks DISABLE TRIGGER ALL;
ALTER TABLE damage_tickets DISABLE TRIGGER ALL;
ALTER TABLE demand_forecast DISABLE TRIGGER ALL;
ALTER TABLE deposit_ledger_entries DISABLE TRIGGER ALL;
ALTER TABLE deposits DISABLE TRIGGER ALL;
ALTER TABLE event_calendar DISABLE TRIGGER ALL;
ALTER TABLE finance_acquiring_channels DISABLE TRIGGER ALL;
ALTER TABLE finance_bad_debt_rates DISABLE TRIGGER ALL;
ALTER TABLE finance_credit_customers DISABLE TRIGGER ALL;
ALTER TABLE finance_float_carry DISABLE TRIGGER ALL;
ALTER TABLE finance_param_audits DISABLE TRIGGER ALL;
ALTER TABLE finance_payment_terms DISABLE TRIGGER ALL;
ALTER TABLE finance_report_exports DISABLE TRIGGER ALL;
ALTER TABLE finance_reports DISABLE TRIGGER ALL;
ALTER TABLE finance_tax_configs DISABLE TRIGGER ALL;
ALTER TABLE guest_aliases DISABLE TRIGGER ALL;
ALTER TABLE guest_coupons DISABLE TRIGGER ALL;
ALTER TABLE guest_identities DISABLE TRIGGER ALL;
ALTER TABLE guest_tags DISABLE TRIGGER ALL;
ALTER TABLE guests DISABLE TRIGGER ALL;
ALTER TABLE hotel_channel_bindings DISABLE TRIGGER ALL;
ALTER TABLE hotel_mkt_settings DISABLE TRIGGER ALL;
ALTER TABLE hotels DISABLE TRIGGER ALL;
ALTER TABLE housekeeping_tasks DISABLE TRIGGER ALL;
ALTER TABLE insight_diagnosis_results DISABLE TRIGGER ALL;
ALTER TABLE inventory_allocation DISABLE TRIGGER ALL;
ALTER TABLE invoices DISABLE TRIGGER ALL;
ALTER TABLE ledger_entries DISABLE TRIGGER ALL;
ALTER TABLE linen DISABLE TRIGGER ALL;
ALTER TABLE linen_snapshots DISABLE TRIGGER ALL;
ALTER TABLE mkt_automations DISABLE TRIGGER ALL;
ALTER TABLE mkt_campaigns DISABLE TRIGGER ALL;
ALTER TABLE mkt_coupon_auto_rule DISABLE TRIGGER ALL;
ALTER TABLE mkt_coupon_auto_rule_coupon DISABLE TRIGGER ALL;
ALTER TABLE mkt_coupon_auto_rule_filter DISABLE TRIGGER ALL;
ALTER TABLE mkt_coupon_auto_rule_trigger DISABLE TRIGGER ALL;
ALTER TABLE mkt_coupon_grant_logs DISABLE TRIGGER ALL;
ALTER TABLE mkt_coupon_grants DISABLE TRIGGER ALL;
ALTER TABLE mkt_coupon_redeems DISABLE TRIGGER ALL;
ALTER TABLE mkt_coupon_triggers DISABLE TRIGGER ALL;
ALTER TABLE mkt_coupons DISABLE TRIGGER ALL;
ALTER TABLE mkt_guest_wallets DISABLE TRIGGER ALL;
ALTER TABLE mkt_member_levels DISABLE TRIGGER ALL;
ALTER TABLE mkt_stored_value_plans DISABLE TRIGGER ALL;
ALTER TABLE night_audit_exceptions DISABLE TRIGGER ALL;
ALTER TABLE night_audit_logs DISABLE TRIGGER ALL;
ALTER TABLE oneid_merge_events DISABLE TRIGGER ALL;
ALTER TABLE oneid_phone_conflicts DISABLE TRIGGER ALL;
ALTER TABLE order_items DISABLE TRIGGER ALL;
ALTER TABLE orders DISABLE TRIGGER ALL;
ALTER TABLE ota_settlements DISABLE TRIGGER ALL;
ALTER TABLE pace_snapshot DISABLE TRIGGER ALL;
ALTER TABLE parity_alert DISABLE TRIGGER ALL;
ALTER TABLE payments DISABLE TRIGGER ALL;
ALTER TABLE permissions DISABLE TRIGGER ALL;
ALTER TABLE pms_ar_entries DISABLE TRIGGER ALL;
ALTER TABLE pms_ar_ledgers DISABLE TRIGGER ALL;
ALTER TABLE pms_checkins DISABLE TRIGGER ALL;
ALTER TABLE pms_folio_entries DISABLE TRIGGER ALL;
ALTER TABLE pms_folios DISABLE TRIGGER ALL;
ALTER TABLE pms_group_room_blocks DISABLE TRIGGER ALL;
ALTER TABLE pms_group_room_lines DISABLE TRIGGER ALL;
ALTER TABLE pms_id_doc_audits DISABLE TRIGGER ALL;
ALTER TABLE pms_room_assignments DISABLE TRIGGER ALL;
ALTER TABLE price_suggestions DISABLE TRIGGER ALL;
ALTER TABLE pricing_assistant_config DISABLE TRIGGER ALL;
ALTER TABLE pricing_decision DISABLE TRIGGER ALL;
ALTER TABLE pricing_effect DISABLE TRIGGER ALL;
ALTER TABLE pricing_recommendation DISABLE TRIGGER ALL;
ALTER TABLE profit_insights DISABLE TRIGGER ALL;
ALTER TABLE rate_strategies DISABLE TRIGGER ALL;
ALTER TABLE recon_batches DISABLE TRIGGER ALL;
ALTER TABLE recon_items DISABLE TRIGGER ALL;
ALTER TABLE refund_adjust_audits DISABLE TRIGGER ALL;
ALTER TABLE refund_adjust_configs DISABLE TRIGGER ALL;
ALTER TABLE refund_adjust_tickets DISABLE TRIGGER ALL;
ALTER TABLE reservations DISABLE TRIGGER ALL;
ALTER TABLE restock_items DISABLE TRIGGER ALL;
ALTER TABLE restock_orders DISABLE TRIGGER ALL;
ALTER TABLE revenue_anomalies DISABLE TRIGGER ALL;
ALTER TABLE reviews DISABLE TRIGGER ALL;
ALTER TABLE risk_alerts DISABLE TRIGGER ALL;
ALTER TABLE role_permissions DISABLE TRIGGER ALL;
ALTER TABLE roles DISABLE TRIGGER ALL;
ALTER TABLE room_inspections DISABLE TRIGGER ALL;
ALTER TABLE room_iot_metrics DISABLE TRIGGER ALL;
ALTER TABLE room_night_inventory DISABLE TRIGGER ALL;
ALTER TABLE room_status_log DISABLE TRIGGER ALL;
ALTER TABLE room_type_base_rate DISABLE TRIGGER ALL;
ALTER TABLE room_types DISABLE TRIGGER ALL;
ALTER TABLE rooms DISABLE TRIGGER ALL;
ALTER TABLE segment_members DISABLE TRIGGER ALL;
ALTER TABLE segments DISABLE TRIGGER ALL;
ALTER TABLE shift_asset_counts DISABLE TRIGGER ALL;
ALTER TABLE shift_audit_logs DISABLE TRIGGER ALL;
ALTER TABLE shift_float_counts DISABLE TRIGGER ALL;
ALTER TABLE shift_handover_tasks DISABLE TRIGGER ALL;
ALTER TABLE shift_handovers DISABLE TRIGGER ALL;
ALTER TABLE shift_receive_diffs DISABLE TRIGGER ALL;
ALTER TABLE staff_roster_templates DISABLE TRIGGER ALL;
ALTER TABLE staff_shift_requests DISABLE TRIGGER ALL;
ALTER TABLE staff_shifts DISABLE TRIGGER ALL;
ALTER TABLE stock_movements DISABLE TRIGGER ALL;
ALTER TABLE supplies DISABLE TRIGGER ALL;
ALTER TABLE supply_alerts DISABLE TRIGGER ALL;
ALTER TABLE supply_categories DISABLE TRIGGER ALL;
ALTER TABLE supply_insights DISABLE TRIGGER ALL;
ALTER TABLE supply_requisitions DISABLE TRIGGER ALL;
ALTER TABLE tag_definitions DISABLE TRIGGER ALL;
ALTER TABLE tax_filings DISABLE TRIGGER ALL;
ALTER TABLE users DISABLE TRIGGER ALL;
ALTER TABLE venue_bookings DISABLE TRIGGER ALL;
ALTER TABLE venues DISABLE TRIGGER ALL;
ALTER TABLE wecom_bind_tickets DISABLE TRIGGER ALL;
ALTER TABLE wecom_callback_events DISABLE TRIGGER ALL;
ALTER TABLE wecom_msg_tasks DISABLE TRIGGER ALL;
ALTER TABLE wx_landing_pages DISABLE TRIGGER ALL;
ALTER TABLE wx_landing_templates DISABLE TRIGGER ALL;
