# SPDX-License-Identifier: Apache-2.0
"""
订单&入住&账单&AR 核心域重构（对齐设计文档五大主表）。

物理策略：
- orders 表扩展为逻辑 pms_order（不改表名，兼容现有 API）
- 新建 pms_checkins / pms_folios / pms_folio_entries / pms_ar_ledgers / pms_ar_entries
- payments 扩展为逻辑 pms_payment（小票号、结算类型、folio_id）
- corp_accounts 补授信字段

幂等：可重复执行；已存在列/表跳过；回填仅补缺。
"""

from __future__ import annotations

from datetime import datetime
from decimal import Decimal

from sqlalchemy import inspect, text
from sqlalchemy.orm import Session

ORDER_COLS = [
    ("order_type", "SMALLINT DEFAULT 1"),
    ("agreement_id", "INTEGER"),
    ("rate_strategy", "VARCHAR(20) DEFAULT 'daily'"),
    ("one_id", "VARCHAR(64)"),
    ("guest_phone", "VARCHAR(20)"),
    ("deposit_amount", "NUMERIC(12,2) DEFAULT 0"),
    ("allow_on_account", "BOOLEAN DEFAULT FALSE"),
    ("credit_occupy", "NUMERIC(12,2) DEFAULT 0"),
    ("longstay_cycle", "VARCHAR(20)"),
    ("monthly_rent", "NUMERIC(12,2)"),
    ("longstay_start", "DATE"),
    ("longstay_end", "DATE"),
    ("skip_daily_room_charge", "BOOLEAN DEFAULT FALSE"),
    ("channel_prepaid", "BOOLEAN DEFAULT FALSE"),
]

PAYMENT_COLS = [
    ("folio_id", "INTEGER"),
    ("received_amount", "NUMERIC(12,2)"),
    ("pos_slip_no", "VARCHAR(60)"),
    ("settle_type", "VARCHAR(20) DEFAULT 'full'"),
    ("note", "TEXT"),
]

CORP_COLS = [
    ("credit_limit", "NUMERIC(14,2) DEFAULT 0"),
    ("credit_used", "NUMERIC(14,2) DEFAULT 0"),
    ("settle_cycle", "VARCHAR(20) DEFAULT 'monthly'"),
]

CHECKIN_COLS = [
    ("guest_name", "VARCHAR(80)"),
    ("id_doc_cipher", "TEXT"),
    ("id_doc_mask", "VARCHAR(40)"),
    ("id_doc_hash", "VARCHAR(64)"),
]

ID_DOC_AUDIT_SQL = """
CREATE TABLE IF NOT EXISTS pms_id_doc_audits (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hotel_id INTEGER NOT NULL REFERENCES hotels(id) ON DELETE CASCADE,
    checkin_id INTEGER REFERENCES pms_checkins(id) ON DELETE SET NULL,
    order_id INTEGER REFERENCES orders(id) ON DELETE SET NULL,
    operator_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    action VARCHAR(40) DEFAULT 'reveal',
    reason VARCHAR(200),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
"""

GUEST_PHONE_COLS = [
    ("phone_cipher", "TEXT"),
    ("phone_mask", "VARCHAR(20)"),
    ("phone_hash", "VARCHAR(64)"),
]
NEW_TABLES_SQL = [
    """
    CREATE TABLE IF NOT EXISTS pms_checkins (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        hotel_id INTEGER NOT NULL REFERENCES hotels(id) ON DELETE CASCADE,
        order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
        reservation_id INTEGER REFERENCES reservations(id) ON DELETE SET NULL,
        room_id INTEGER REFERENCES rooms(id) ON DELETE SET NULL,
        guest_id INTEGER REFERENCES guests(id) ON DELETE SET NULL,
        status VARCHAR(20) DEFAULT 'inhouse',
        actual_checkin_at TIMESTAMP,
        actual_checkout_at TIMESTAMP,
        id_doc_type VARCHAR(20),
        id_doc_cipher TEXT,
        id_doc_mask VARCHAR(40),
        id_doc_hash VARCHAR(64),
        id_doc_no VARCHAR(40),
        guest_name VARCHAR(80),
        face_registered BOOLEAN DEFAULT FALSE,
        floor SMALLINT,
        room_no VARCHAR(20),
        master_checkin_id INTEGER REFERENCES pms_checkins(id) ON DELETE SET NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS pms_room_assignments (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        hotel_id INTEGER NOT NULL REFERENCES hotels(id) ON DELETE CASCADE,
        order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
        checkin_id INTEGER REFERENCES pms_checkins(id) ON DELETE SET NULL,
        from_room_id INTEGER REFERENCES rooms(id) ON DELETE SET NULL,
        to_room_id INTEGER REFERENCES rooms(id) ON DELETE SET NULL,
        assign_type VARCHAR(20) NOT NULL DEFAULT 'pre_assign',
        operator_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
        reason VARCHAR(200),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS pms_folios (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        hotel_id INTEGER NOT NULL REFERENCES hotels(id) ON DELETE CASCADE,
        folio_no VARCHAR(40) NOT NULL UNIQUE,
        order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
        checkin_id INTEGER REFERENCES pms_checkins(id) ON DELETE SET NULL,
        guest_id INTEGER REFERENCES guests(id) ON DELETE SET NULL,
        status VARCHAR(20) DEFAULT 'open',
        balance NUMERIC(12,2) DEFAULT 0,
        charge_total NUMERIC(12,2) DEFAULT 0,
        payment_total NUMERIC(12,2) DEFAULT 0,
        opened_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        closed_at TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS pms_folio_entries (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        folio_id INTEGER NOT NULL REFERENCES pms_folios(id) ON DELETE CASCADE,
        entry_type VARCHAR(30) NOT NULL,
        biz_date DATE,
        description VARCHAR(160),
        amount NUMERIC(12,2) NOT NULL DEFAULT 0,
        qty NUMERIC(8,2) DEFAULT 1,
        unit_price NUMERIC(10,2),
        source VARCHAR(30) DEFAULT 'manual',
        operator_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS pms_ar_ledgers (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        hotel_id INTEGER NOT NULL REFERENCES hotels(id) ON DELETE CASCADE,
        corp_id INTEGER NOT NULL REFERENCES corp_accounts(id) ON DELETE CASCADE,
        charged_total NUMERIC(14,2) DEFAULT 0,
        settled_total NUMERIC(14,2) DEFAULT 0,
        balance NUMERIC(14,2) DEFAULT 0,
        credit_limit NUMERIC(14,2) DEFAULT 0,
        credit_used NUMERIC(14,2) DEFAULT 0,
        settle_cycle VARCHAR(20) DEFAULT 'monthly',
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UNIQUE(hotel_id, corp_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS pms_ar_entries (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ar_ledger_id INTEGER NOT NULL REFERENCES pms_ar_ledgers(id) ON DELETE CASCADE,
        entry_type VARCHAR(20) NOT NULL,
        order_id INTEGER REFERENCES orders(id) ON DELETE SET NULL,
        folio_id INTEGER REFERENCES pms_folios(id) ON DELETE SET NULL,
        amount NUMERIC(12,2) NOT NULL,
        ref_no VARCHAR(80),
        note TEXT,
        operator_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """,
]


def _add_cols(engine, table: str, cols: list[tuple[str, str]]) -> int:
    insp = inspect(engine)
    if not insp.has_table(table):
        return 0
    existing = {c["name"] for c in insp.get_columns(table)}
    n = 0
    with engine.begin() as conn:
        for name, ddl in cols:
            if name in existing:
                continue
            conn.execute(text(f"ALTER TABLE {table} ADD COLUMN {name} {ddl}"))
            n += 1
    return n


def ensure_pms_core_schema(engine) -> dict:
    added = {
        "orders": _add_cols(engine, "orders", ORDER_COLS),
        "payments": _add_cols(engine, "payments", PAYMENT_COLS),
        "corp_accounts": _add_cols(engine, "corp_accounts", CORP_COLS),
    }
    with engine.begin() as conn:
        for sql in NEW_TABLES_SQL:
            conn.execute(text(sql))
        conn.execute(text(ID_DOC_AUDIT_SQL))
    added["pms_checkins"] = _add_cols(engine, "pms_checkins", CHECKIN_COLS)
    added["guests"] = _add_cols(engine, "guests", GUEST_PHONE_COLS)
    return added


def migrate_plaintext_phones(db: Session, hotel_id: int = 1) -> int:
    """将客人明文手机号迁入密文/掩码，phone 列改为脱敏。"""
    from infra.id_doc_crypto import mask_phone, normalize_phone, pack_phone_fields
    from models import Guest

    n = 0
    for g in db.query(Guest).all():
        raw = normalize_phone(g.phone)
        if not raw:
            continue
        # 已是脱敏形态则跳过（无 cipher 时仍可补）
        if getattr(g, "phone_cipher", None) and ("*" in str(g.phone or "")):
            continue
        if getattr(g, "phone_cipher", None):
            if g.phone and "*" not in str(g.phone):
                g.phone = mask_phone(raw)
                n += 1
            continue
        packed = pack_phone_fields(raw, hotel_id=hotel_id)
        g.phone_cipher = packed["phone_cipher"]
        g.phone_mask = packed["phone_mask"]
        g.phone_hash = packed["phone_hash"]
        g.phone = packed["phone"]
        n += 1
    if n:
        db.flush()
    return n


def migrate_plaintext_id_docs(db: Session) -> int:
    """将遗留明文 id_doc_no 迁入密文/掩码，并清空明文。"""
    from infra.id_doc_crypto import pack_id_doc_fields
    from models import PmsCheckin

    n = 0
    rows = db.query(PmsCheckin).filter(PmsCheckin.id_doc_no.isnot(None)).all()
    for ci in rows:
        plain = (ci.id_doc_no or "").strip()
        if not plain:
            continue
        if not ci.id_doc_cipher:
            packed = pack_id_doc_fields(plain, hotel_id=ci.hotel_id)
            ci.id_doc_cipher = packed["id_doc_cipher"]
            ci.id_doc_mask = packed["id_doc_mask"] or ci.id_doc_mask
            ci.id_doc_hash = packed["id_doc_hash"]
        ci.id_doc_no = None
        n += 1
    if n:
        db.flush()
    return n


def purge_expired_id_docs(db: Session, retain_years: int = 5) -> int:
    """离店超过 retain_years 的入住登记：清空证件密文/哈希，保留掩码。"""
    from datetime import timedelta

    from models import PmsCheckin

    cutoff = datetime.now() - timedelta(days=365 * max(1, int(retain_years or 5)))
    n = 0
    q = (
        db.query(PmsCheckin)
        .filter(
            PmsCheckin.status == "checked_out",
            PmsCheckin.actual_checkout_at.isnot(None),
            PmsCheckin.actual_checkout_at < cutoff,
            PmsCheckin.id_doc_cipher.isnot(None),
        )
        .all()
    )
    for ci in q:
        ci.id_doc_cipher = None
        ci.id_doc_hash = None
        ci.id_doc_no = None
        # id_doc_mask 保留便于历史列表展示
        n += 1
    if n:
        db.flush()
    return n


def backfill_pms_core(db: Session) -> dict:
    """回填订单类型/协议/长住标记，并为在住/已退订单补 checkin+folio。"""
    from infra.order_seed_helpers import _infer_order_type
    from models import (
        Channel,
        CorpAccount,
        Guest,
        Order,
        OrderItem,
        Payment,
        PmsArEntry,
        PmsArLedger,
        PmsCheckin,
        PmsFolio,
        PmsFolioEntry,
        Reservation,
        Room,
    )
    from orders.channel_config import source_group_for

    channels = {c.id: c for c in db.query(Channel).all()}
    corps = {(c.hotel_id, c.code): c for c in db.query(CorpAccount).all()}
    # 每酒店默认协议户（若有）
    default_corp = {}
    for c in db.query(CorpAccount).filter_by(status="active").all():
        default_corp.setdefault(c.hotel_id, c)

    updated = 0
    checkins = 0
    folios = 0
    ar_n = 0

    for o in db.query(Order).all():
        ch = channels.get(o.channel_id)
        code = ch.code if ch else None
        nights = int(o.nights or 0)
        sg = source_group_for(ch, nights)
        ot = _infer_order_type(code, sg, nights)

        dirty = False
        if getattr(o, "order_type", None) in (None, 0):
            o.order_type = ot
            dirty = True
        elif o.order_type == 1 and ot != 1:
            # 仅在仍为默认散客时纠正
            o.order_type = ot
            dirty = True

        g = db.get(Guest, o.guest_id) if o.guest_id else None
        if g:
            if not o.one_id and getattr(g, "one_id", None):
                o.one_id = g.one_id
                dirty = True
            if not o.guest_phone and g.phone:
                o.guest_phone = g.phone
                dirty = True

        if ot == 2 and not o.channel_prepaid:
            o.channel_prepaid = True
            dirty = True
        if ot == 3:
            o.allow_on_account = True
            o.rate_strategy = "agreement"
            if not o.agreement_id:
                corp = default_corp.get(o.hotel_id)
                if corp:
                    o.agreement_id = corp.id
            dirty = True
        if ot == 4:
            o.rate_strategy = "monthly"
            o.skip_daily_room_charge = True
            o.longstay_cycle = o.longstay_cycle or "monthly"
            if o.monthly_rent is None:
                o.monthly_rent = o.total_amount
            if not o.longstay_start:
                o.longstay_start = o.check_in
            if not o.longstay_end:
                o.longstay_end = o.check_out
            dirty = True
        if dirty:
            updated += 1

        if o.status not in ("checked_in", "checked_out", "partial_extend"):
            continue

        existing_ci = db.query(PmsCheckin).filter_by(order_id=o.id).first()
        if existing_ci:
            ci = existing_ci
        else:
            res = db.query(Reservation).filter_by(order_id=o.id).first()
            room = db.get(Room, res.room_id) if res and res.room_id else None
            ci = PmsCheckin(
                hotel_id=o.hotel_id,
                order_id=o.id,
                reservation_id=res.id if res else None,
                room_id=room.id if room else None,
                guest_id=o.guest_id,
                status="checked_out" if o.status == "checked_out" else "inhouse",
                actual_checkin_at=datetime.combine(o.check_in, datetime.min.time()) if o.check_in else datetime.now(),
                actual_checkout_at=(
                    datetime.combine(o.check_out, datetime.min.time())
                    if o.status == "checked_out" and o.check_out
                    else None
                ),
                floor=room.floor if room else None,
                room_no=room.room_no if room else None,
            )
            db.add(ci)
            db.flush()
            checkins += 1

        folio = db.query(PmsFolio).filter_by(order_id=o.id).first()
        if not folio:
            folio = PmsFolio(
                hotel_id=o.hotel_id,
                folio_no=f"F{o.id:08d}",
                order_id=o.id,
                checkin_id=ci.id,
                guest_id=o.guest_id,
                status="closed"
                if o.status == "checked_out" and o.payment_status == "paid"
                else ("partial" if o.payment_status in ("partial", "on_account") else "open"),
                opened_at=ci.actual_checkin_at or datetime.now(),
                closed_at=ci.actual_checkout_at if o.status == "checked_out" else None,
            )
            db.add(folio)
            db.flush()
            folios += 1

            items = db.query(OrderItem).filter_by(order_id=o.id).all()
            charge = Decimal("0")
            if items:
                for it in items:
                    et = "room_charge" if (it.item_type or "") == "room" else "misc"
                    amt = Decimal(str(it.amount or 0))
                    charge += amt
                    db.add(
                        PmsFolioEntry(
                            folio_id=folio.id,
                            entry_type=et,
                            biz_date=o.check_in,
                            description=it.description or et,
                            amount=amt,
                            qty=it.qty or 1,
                            unit_price=it.unit_price,
                            source="system",
                        )
                    )
            else:
                amt = Decimal(str(o.total_amount or 0))
                charge = amt
                db.add(
                    PmsFolioEntry(
                        folio_id=folio.id,
                        entry_type="room_charge",
                        biz_date=o.check_in,
                        description="房费（回填）",
                        amount=amt,
                        source="system",
                    )
                )

            pays = db.query(Payment).filter_by(order_id=o.id).all()
            pay_total = Decimal("0")
            for p in pays:
                if not p.folio_id:
                    p.folio_id = folio.id
                if p.received_amount is None:
                    p.received_amount = p.amount
                if not p.settle_type:
                    p.settle_type = "full"
                pay_total += Decimal(str(p.amount or 0))

            # OTA 预付：记一笔渠道预付冲减（余额仅杂费）
            if o.channel_prepaid and o.payment_status == "paid" and not pays:
                pay_total = charge
                db.add(
                    PmsFolioEntry(
                        folio_id=folio.id,
                        entry_type="adjustment",
                        biz_date=o.check_in,
                        description="渠道预付冲减",
                        amount=-charge,
                        source="system",
                    )
                )
                charge_net = Decimal("0")
            else:
                charge_net = charge

            folio.charge_total = charge
            folio.payment_total = pay_total
            folio.balance = max(Decimal("0"), charge_net - pay_total)

            # 协议挂账 → AR
            if o.payment_status == "on_account" and o.agreement_id:
                ledger = db.query(PmsArLedger).filter_by(hotel_id=o.hotel_id, corp_id=o.agreement_id).first()
                if not ledger:
                    corp = db.get(CorpAccount, o.agreement_id)
                    ledger = PmsArLedger(
                        hotel_id=o.hotel_id,
                        corp_id=o.agreement_id,
                        credit_limit=getattr(corp, "credit_limit", None) or Decimal("200000"),
                        settle_cycle=getattr(corp, "settle_cycle", None) or "monthly",
                    )
                    db.add(ledger)
                    db.flush()
                exist_ar = (
                    db.query(PmsArEntry).filter_by(ar_ledger_id=ledger.id, order_id=o.id, entry_type="charge").first()
                )
                if not exist_ar:
                    amt = Decimal(str(o.total_amount or 0))
                    db.add(
                        PmsArEntry(
                            ar_ledger_id=ledger.id,
                            entry_type="charge",
                            order_id=o.id,
                            folio_id=folio.id,
                            amount=amt,
                            note="历史挂账回填",
                        )
                    )
                    ledger.charged_total = Decimal(str(ledger.charged_total or 0)) + amt
                    ledger.balance = Decimal(str(ledger.balance or 0)) + amt
                    ledger.credit_used = Decimal(str(ledger.credit_used or 0)) + amt
                    o.credit_occupy = amt
                    ar_n += 1

    # 为每个协议企业确保 AR 主档
    for corp in db.query(CorpAccount).all():
        led = db.query(PmsArLedger).filter_by(hotel_id=corp.hotel_id, corp_id=corp.id).first()
        if not led:
            if not corp.credit_limit:
                corp.credit_limit = Decimal("200000")
            db.add(
                PmsArLedger(
                    hotel_id=corp.hotel_id,
                    corp_id=corp.id,
                    credit_limit=corp.credit_limit or Decimal("200000"),
                    settle_cycle=corp.settle_cycle or "monthly",
                )
            )

    db.commit()
    return {
        "orders_updated": updated,
        "checkins_created": checkins,
        "folios_created": folios,
        "ar_charges": ar_n,
    }
