// SPDX-License-Identifier: Apache-2.0
// 自动生成，勿手改。重新生成：node scripts/gen_routes.mjs
export interface PageMeta {
  domain: string
  route: string
  title: string
}
export const pageManifest: PageMeta[] = [
  { domain: 'AI 中台', route: '/a-ai-core/ai-command-center', title: 'Ai Command Center' },
  {
    domain: 'AI 中台',
    route: '/a-ai-core/ai-negative-review-warning',
    title: 'Ai Negative Review Warning',
  },
  { domain: 'AI 中台', route: '/a-ai-core/ai-reputation-ai', title: 'Ai Reputation Ai' },
  {
    domain: 'AI 中台',
    route: '/a-ai-core/ai-system-configuration',
    title: 'Ai System Configuration',
  },
  { domain: 'AI 中台', route: '/a-ai-core/map-config', title: 'Map Config' },
  { domain: 'AI 中台', route: '/a-ai-core/private-channel', title: 'Private Channel' },
  { domain: 'AI 中台', route: '/a-ai-core/wecom-integration', title: 'Wecom Integration' },
  { domain: 'AI 中台', route: '/a-ai-core/ai-workbench', title: 'Ai Workbench' },
  {
    domain: 'AI 中台',
    route: '/a-ai-core/automated-appeal-workspace',
    title: 'Automated Appeal Workspace',
  },
  { domain: 'AI 中台', route: '/a-ai-core/center', title: 'Center' },
  {
    domain: 'AI 中台',
    route: '/a-ai-core/finance-params-float-carry',
    title: 'Finance Params Float Carry',
  },
  {
    domain: 'AI 中台',
    route: '/a-ai-core/intelligent-operations-workflow',
    title: 'Intelligent Operations Workflow',
  },
  { domain: 'AI 中台', route: '/a-ai-core/kiosk', title: 'Kiosk' },
  { domain: 'AI 中台', route: '/a-ai-core/manager-ai-assistant', title: 'Manager Ai Assistant' },
  { domain: 'AI 中台', route: '/a-ai-core/monitor', title: 'Monitor' },
  {
    domain: 'AI 中台',
    route: '/a-ai-core/official-recommendations',
    title: 'Official Recommendations',
  },
  {
    domain: 'AI 中台',
    route: '/a-ai-core/finance-params-float-carry?tab=ota',
    title: 'Ota Commission (财务参数)',
  },
  { domain: 'AI 中台', route: '/a-ai-core/roi', title: 'Roi' },
  { domain: 'AI 中台', route: '/a-ai-core/room-master', title: 'Room Master' },
  { domain: 'AI 中台', route: '/a-ai-core/room-type-management', title: 'Room Type Management' },
  { domain: 'AI 中台', route: '/a-ai-core/triggers', title: 'Triggers' },
  { domain: 'acquisition', route: '/acquisition/AcquisitionShell', title: 'AcquisitionShell' },
  { domain: 'acquisition', route: '/acquisition/AiSeedingPanel', title: 'AiSeedingPanel' },
  { domain: 'acquisition', route: '/acquisition/PrivateDomainPanel', title: 'PrivateDomainPanel' },
  { domain: 'acquisition', route: '/acquisition/PublicAdsPanel', title: 'PublicAdsPanel' },
  { domain: 'acquisition', route: '/acquisition/SegmentsPanel', title: 'SegmentsPanel' },
  { domain: 'analytics', route: '/analytics/hub', title: 'Hub' },
  { domain: 'analytics', route: '/analytics/yield-overview', title: 'Yield Overview' },
  {
    domain: '数据底座',
    route: '/b-data/5-3-4-0-global-sync-health',
    title: '5 3 4 0 Global Sync Health',
  },
  { domain: '数据底座', route: '/b-data/add-channel', title: 'Add Channel' },
  { domain: '数据底座', route: '/b-data/ai-auto-awesome', title: 'Ai Auto Awesome' },
  { domain: '数据底座', route: '/b-data/ai-high-confidence-94', title: 'Ai High Confidence 94' },
  { domain: '数据底座', route: '/b-data/channel-sync-overview', title: 'Channel Sync Overview' },
  { domain: '数据底座', route: '/b-data/cohort-list', title: 'Cohort List' },
  {
    domain: '数据底座',
    route: '/b-data/consolidated-asset-confirmation',
    title: 'Consolidated Asset Confirmation',
  },
  { domain: '数据底座', route: '/b-data/data-source-lineage', title: 'Data Source Lineage' },
  { domain: '数据底座', route: '/b-data/f-ngm-nl-pms', title: 'F Ngm Nl Pms' },
  { domain: '数据底座', route: '/b-data/global-guest-directory', title: 'Global Guest Directory' },
  { domain: '数据底座', route: '/b-data/guest-360-workspace', title: 'Guest 360 Workspace' },
  { domain: '数据底座', route: '/b-data/guest-segmentation', title: 'Guest Segmentation' },
  { domain: '数据底座', route: '/b-data/life-time-value', title: 'Life Time Value' },
  { domain: '数据底座', route: '/b-data/ltv', title: 'Ltv' },
  { domain: '数据底座', route: '/b-data/master-tag-library', title: 'Master Tag Library' },
  { domain: '数据底座', route: '/b-data/one-id-audit', title: 'One Id Audit' },
  { domain: '数据底座', route: '/b-data/one-id-resolution', title: 'One Id Resolution' },
  { domain: '数据底座', route: '/b-data/one-id', title: 'One Id' },
  { domain: '数据底座', route: '/b-data/ota', title: 'Ota' },
  { domain: '数据底座', route: '/b-data/pms', title: 'Pms' },
  { domain: '数据底座', route: '/b-data/prediction', title: 'Prediction' },
  { domain: '数据底座', route: '/b-data/search', title: 'Search' },
  { domain: '数据底座', route: '/b-data/semantic-tag-rules', title: 'Semantic Tag Rules' },
  { domain: '数据底座', route: '/b-data/system-operational-2', title: 'System Operational 2' },
  { domain: '数据底座', route: '/b-data/system-operational', title: 'System Operational' },
  { domain: '数据底座', route: '/b-data/tag-ecosystem-overview', title: 'Tag Ecosystem Overview' },
  { domain: '数据底座', route: '/b-data/tag-management', title: 'Tag Management' },
  { domain: '数据底座', route: '/b-data/top-50-2', title: 'Top 50 2' },
  { domain: '数据底座', route: '/b-data/top-50', title: 'Top 50' },
  { domain: '收益管理', route: '/c1-revenue/30-auto-awesome-ai', title: '30 Auto Awesome Ai' },
  { domain: '收益管理', route: '/c1-revenue/365-revpar', title: '365 Revpar' },
  { domain: '收益管理', route: '/c1-revenue/ai-workbench', title: 'Ai Workbench' },
  { domain: '收益管理', route: '/c1-revenue/allotment-strategy', title: 'Allotment Strategy' },
  {
    domain: '收益管理',
    route: '/c1-revenue/auto-awesome-ai-generated-2',
    title: 'Auto Awesome Ai Generated 2',
  },
  {
    domain: '收益管理',
    route: '/c1-revenue/auto-awesome-ai-generated',
    title: 'Auto Awesome Ai Generated',
  },
  {
    domain: '收益管理',
    route: '/c1-revenue/cold-start-strategies',
    title: 'Cold Start Strategies',
  },
  { domain: '收益管理', route: '/c1-revenue/guardrails-sync', title: 'Guardrails Sync' },
  { domain: '收益管理', route: '/c1-revenue/inventory-allocation', title: 'Inventory Allocation' },
  { domain: '收益管理', route: '/c1-revenue/mape', title: 'Mape' },
  {
    domain: '收益管理',
    route: '/c1-revenue/net-effective-revenue',
    title: 'Net Effective Revenue',
  },
  { domain: '收益管理', route: '/c1-revenue/pa_4', title: 'Pa 4' },
  { domain: '收益管理', route: '/c1-revenue/pa_5_2', title: 'Pa 5 2' },
  { domain: '收益管理', route: '/c1-revenue/pms-2', title: 'Pms 2' },
  { domain: '收益管理', route: '/c1-revenue/pms', title: 'Pms' },
  { domain: '收益管理', route: '/c1-revenue/price-assistant', title: 'Price Assistant' },
  { domain: '收益管理', route: '/c1-revenue/room-board-2', title: 'Room Board 2' },
  { domain: '收益管理', route: '/c1-revenue/room-board', title: 'Room Board' },
  { domain: '收益管理', route: '/c1-revenue/strategy', title: 'Strategy' },
  { domain: '收益管理', route: '/c1-revenue/variables', title: 'Variables' },
  { domain: '收益管理', route: '/c1-revenue/yield-prediction', title: 'Yield Prediction' },
  { domain: '多形态多门店', route: '/c10-multiformat/3d-layout', title: '3d Layout' },
  {
    domain: '多形态多门店',
    route: '/c10-multiformat/mice-intelligence',
    title: 'Mice Intelligence',
  },
  { domain: '多形态多门店', route: '/c10-multiformat/mice', title: 'Mice' },
  { domain: '多形态多门店', route: '/c10-multiformat/room-board', title: 'Room Board' },
  { domain: '多形态多门店', route: '/c10-multiformat/scheduling', title: 'Scheduling' },
  { domain: '多形态多门店', route: '/c10-multiformat/shift-handover', title: 'Shift Handover' },
  { domain: '风控预警', route: '/c2-risk/ai-survival-strategy', title: 'Ai Survival Strategy' },
  { domain: '风控预警', route: '/c2-risk/black-swan-warning', title: 'Black Swan Warning' },
  { domain: '风控预警', route: '/c2-risk/log', title: 'Log' },
  { domain: '风控预警', route: '/c2-risk/nl-command', title: 'Nl Command' },
  { domain: '获客种草', route: '/c3-acquisition/5-2-4-geo', title: '5 2 4 Geo' },
  {
    domain: '获客种草',
    route: '/c3-acquisition/ai-engine-optimization',
    title: 'Ai Engine Optimization',
  },
  {
    domain: '获客种草',
    route: '/c3-acquisition/ai-xiaohongshu-analytics',
    title: 'Ai Xiaohongshu Analytics',
  },
  {
    domain: '获客种草',
    route: '/c3-acquisition/auto-awesome-ai-active',
    title: 'Auto Awesome Ai Active',
  },
  { domain: '获客种草', route: '/c3-acquisition/competitor-set', title: 'Competitor Set' },
  { domain: '获客种草', route: '/c3-acquisition/content-ai', title: 'Content Ai' },
  { domain: '获客种草', route: '/c3-acquisition/douyin-acquisition', title: 'Douyin Acquisition' },
  { domain: '获客种草', route: '/c3-acquisition/filter-list', title: 'Filter List' },
  { domain: '获客种草', route: '/c3-acquisition/flow', title: 'Flow' },
  {
    domain: '获客种草',
    route: '/c3-acquisition/geo-attribution-roi',
    title: 'Geo Attribution Roi',
  },
  { domain: '获客种草', route: '/c3-acquisition/geo', title: 'Geo' },
  { domain: '获客种草', route: '/c3-acquisition/geofencing', title: 'Geofencing' },
  { domain: '获客种草', route: '/c3-acquisition/one-id', title: 'One Id' },
  { domain: '获客种草', route: '/c3-acquisition/ota-2', title: 'Ota 2' },
  { domain: '获客种草', route: '/c3-acquisition/ota-3', title: 'Ota 3' },
  { domain: '获客种草', route: '/c3-acquisition/ota', title: 'Ota' },
  { domain: '获客种草', route: '/c3-acquisition/poi', title: 'Poi' },
  { domain: '获客种草', route: '/c3-acquisition/room-board-2', title: 'Room Board 2' },
  { domain: '获客种草', route: '/c3-acquisition/room-board', title: 'Room Board' },
  {
    domain: '获客种草',
    route: '/c3-acquisition/wecom-mini-program-direct-sales',
    title: 'Wecom Mini Program Direct Sales',
  },
  {
    domain: '获客种草',
    route: '/c3-acquisition/xiaohongshu-native-analytics',
    title: 'Xiaohongshu Native Analytics',
  },
  {
    domain: '口碑关系',
    route: '/c4-reputation/auto-awesome-ai-verified',
    title: 'Auto Awesome Ai Verified',
  },
  { domain: '口碑关系', route: '/c4-reputation/download', title: 'Download' },
  { domain: '口碑关系', route: '/c4-reputation/ltv', title: 'Ltv' },
  {
    domain: '口碑关系',
    route: '/c4-reputation/one-id-tracing-path-to-purchase',
    title: 'One Id Tracing Path To Purchase',
  },
  { domain: '口碑关系', route: '/c4-reputation/roi', title: 'Roi' },
  { domain: '口碑关系', route: '/c4-reputation/room-board', title: 'Room Board' },
  { domain: '前台订单', route: '/c5-frontdesk/5.5.3.1', title: '5.5.3.1' },
  { domain: '前台订单', route: '/c5-frontdesk/agreement-corp', title: 'Agreement Corp' },
  { domain: '前台订单', route: '/c5-frontdesk/ai-new', title: 'Ai New' },
  { domain: '前台订单', route: '/c5-frontdesk/cashiering-checkout', title: 'Cashiering Checkout' },
  { domain: '前台订单', route: '/c5-frontdesk/engine', title: 'Engine' },
  { domain: '前台订单', route: '/c5-frontdesk/filter', title: 'Filter' },
  { domain: '前台订单', route: '/c5-frontdesk/float', title: 'Float' },
  { domain: '前台订单', route: '/c5-frontdesk/front-desk-booking', title: 'Front Desk Booking' },
  { domain: '前台订单', route: '/c5-frontdesk/group-booking', title: 'Group Booking' },
  { domain: '前台订单', route: '/c5-frontdesk/housekeeping', title: 'Housekeeping' },
  { domain: '前台订单', route: '/c5-frontdesk/ooo', title: 'Ooo' },
  { domain: '前台订单', route: '/c5-frontdesk/order-attribution', title: 'Order Attribution' },
  { domain: '前台订单', route: '/c5-frontdesk/order-monitor-2', title: 'Order Monitor 2' },
  { domain: '前台订单', route: '/c5-frontdesk/order-monitor', title: 'Order Monitor' },
  { domain: '前台订单', route: '/c5-frontdesk/order-ops', title: 'Order Ops' },
  { domain: '前台订单', route: '/c5-frontdesk/orders', title: 'Orders' },
  { domain: '前台订单', route: '/c5-frontdesk/pending-assignment', title: 'Pending Assignment' },
  { domain: '前台订单', route: '/c5-frontdesk/rc-print', title: 'Rc Print' },
  {
    domain: '前台订单',
    route: '/c5-frontdesk/room-asset-configuration',
    title: 'Room Asset Configuration',
  },
  { domain: '前台订单', route: '/c5-frontdesk/room-board', title: 'Room Board' },
  { domain: '前台订单', route: '/c5-frontdesk/smart-inventory', title: 'Smart Inventory' },
  {
    domain: '前台订单',
    route: '/c5-frontdesk/voucher-verification',
    title: 'Voucher Verification',
  },
  {
    domain: '前台订单',
    route: '/c5-frontdesk/walk-in-quick-check-in',
    title: 'Walk In Quick Check In',
  },
  { domain: '前台订单', route: '/c5-frontdesk/zhang-san', title: 'Zhang San' },
  { domain: '房务运营', route: '/c6-housekeeping/arrow-forward-2', title: 'Arrow Forward 2' },
  { domain: '房务运营', route: '/c6-housekeeping/arrow-forward', title: 'Arrow Forward' },
  { domain: '房务运营', route: '/c6-housekeeping/dispatch', title: 'Dispatch' },
  {
    domain: '房务运营',
    route: '/c6-housekeeping/flexible-staffing-pool',
    title: 'Flexible Staffing Pool',
  },
  {
    domain: '房务运营',
    route: '/c6-housekeeping/gig-style-task-bidding',
    title: 'Gig Style Task Bidding',
  },
  { domain: '房务运营', route: '/c6-housekeeping/housekeeping', title: 'Housekeeping' },
  {
    domain: '房务运营',
    route: '/c6-housekeeping/in-stay-guest-request-management',
    title: 'In Stay Guest Request Management',
  },
  {
    domain: '房务运营',
    route: '/c6-housekeeping/LaborEfficiencyReportPanel',
    title: 'LaborEfficiencyReportPanel',
  },
  {
    domain: '房务运营',
    route: '/c6-housekeeping/long-term-maintenance-schedule-oct-2023',
    title: 'Long Term Maintenance Schedule Oct 2023',
  },
  { domain: '房务运营', route: '/c6-housekeeping/on-demand-labor', title: 'On Demand Labor' },
  { domain: '房务运营', route: '/c6-housekeeping/performance', title: 'Performance' },
  {
    domain: '房务运营',
    route: '/c6-housekeeping/PerformanceReportPanel',
    title: 'PerformanceReportPanel',
  },
  {
    domain: '房务运营',
    route: '/c6-housekeeping/real-time-labor-efficiency',
    title: 'Real Time Labor Efficiency',
  },
  { domain: '房务运营', route: '/c6-housekeeping/reports', title: 'Reports' },
  { domain: '房务运营', route: '/c6-housekeeping/room-302-john-doe', title: 'Room 302 John Doe' },
  { domain: '房务运营', route: '/c6-housekeeping/room-board-2', title: 'Room Board 2' },
  { domain: '房务运营', route: '/c6-housekeeping/room-board-3', title: 'Room Board 3' },
  { domain: '房务运营', route: '/c6-housekeeping/room-board', title: 'Room Board' },
  { domain: '房务运营', route: '/c6-housekeeping/sop', title: 'Sop' },
  { domain: '房务运营', route: '/c6-housekeeping/staffing', title: 'Staffing' },
  { domain: '房务运营', route: '/c6-housekeeping/today', title: 'Today' },
  {
    domain: '房务运营',
    route: '/c6-housekeeping/view-full-incident-log',
    title: 'View Full Incident Log',
  },
  { domain: '房务运营', route: '/c6-housekeeping/vip', title: 'Vip' },
  { domain: '房务运营', route: '/c6-housekeeping/workflow', title: 'Workflow' },
  { domain: '设备设施', route: '/c8-assets/inventory-2', title: 'Inventory 2' },
  {
    domain: '设备设施',
    route: '/c8-assets/loss-analysis-replacement-strategy',
    title: 'Loss Analysis Replacement Strategy',
  },
  { domain: '设备设施', route: '/c8-assets/tracking', title: 'Tracking' },
  { domain: '财务合规', route: '/c9-finance/ar-ap', title: 'Ar Ap' },
  { domain: '财务合规', route: '/c9-finance/daily-operations', title: 'Daily Operations' },
  { domain: '财务合规', route: '/c9-finance/deposit-management', title: 'Deposit Management' },
  { domain: '财务合规', route: '/c9-finance/happy-house', title: 'Happy House' },
  {
    domain: '财务合规',
    route: '/c9-finance/manual-price-override',
    title: 'Manual Price Override',
  },
  { domain: '财务合规', route: '/c9-finance/night-audit-auto-fix', title: 'Night Audit Auto Fix' },
  { domain: '财务合规', route: '/c9-finance/night-audit', title: 'Night Audit' },
  { domain: '财务合规', route: '/c9-finance/pms', title: 'Pms' },
  {
    domain: '财务合规',
    route: '/c9-finance/profit-optimization-ai',
    title: 'Profit Optimization Ai',
  },
  { domain: '财务合规', route: '/c9-finance/refund-adjustment', title: 'Refund Adjustment' },
  { domain: '财务合规', route: '/c9-finance/revenue-forecast', title: 'Revenue Forecast' },
  { domain: '财务合规', route: '/c9-finance/shift-handover', title: 'Shift Handover' },
  { domain: '财务合规', route: '/c9-finance/shift-takeover', title: 'Shift Takeover' },
  { domain: '财务合规', route: '/c9-finance/smart-reconciliation', title: 'Smart Reconciliation' },
  { domain: '平台设置', route: '/d-platform/eco-intelligence', title: 'Eco Intelligence' },
  { domain: '门户工作台', route: '/portal/portal', title: 'Portal' },
  { domain: 'pricing', route: '/pricing/AcceptModal', title: 'AcceptModal' },
  { domain: 'pricing', route: '/pricing/AlertsTab', title: 'AlertsTab' },
  { domain: 'pricing', route: '/pricing/CalendarTab', title: 'CalendarTab' },
  { domain: 'pricing', route: '/pricing/CompetitorMapPicker', title: 'CompetitorMapPicker' },
  { domain: 'pricing', route: '/pricing/CompetitorPanel', title: 'CompetitorPanel' },
  { domain: 'pricing', route: '/pricing/CompetitorTab', title: 'CompetitorTab' },
  { domain: 'pricing', route: '/pricing/ExplainModal', title: 'ExplainModal' },
  { domain: 'pricing', route: '/pricing/OverviewTab', title: 'OverviewTab' },
  { domain: 'pricing', route: '/pricing/ParamsModal', title: 'ParamsModal' },
  { domain: 'pricing', route: '/pricing/SimulateTab', title: 'SimulateTab' },
  { domain: 'pricing', route: '/pricing/SuggestTab', title: 'SuggestTab' },
  { domain: 'pricing', route: '/pricing/TrendTab', title: 'TrendTab' },
  { domain: 'wecom', route: '/wecom/CareSidebar', title: 'CareSidebar' },
  { domain: '设备设施', route: '/c8-assets/assets/:id', title: '资产画像' },
  { domain: '设备设施', route: '/c8-assets/damage-registration', title: '报废登记' },
]
