# SPDX-License-Identifier: Apache-2.0
"""RBAC 服务：建表、种子矩阵、按角色读权限（短缓存）、写回。"""

from __future__ import annotations

import time
from typing import Iterable, Optional

from sqlalchemy import inspect, text
from sqlalchemy.orm import Session

from infra.rbac_catalog import (
    ACTIONS,
    DEFAULT_ACTIONS,
    DEFAULT_MENUS,
    MENUS,
    MODULE_LABELS,
    ROLES,
    SYSTEM_ROLE_CODES,
)
from models import Permission, Role, RolePermission, User

# role_code -> (menus, scopes, ts)
_CACHE: dict[str, tuple[frozenset[str], frozenset[str], float]] = {}
_CACHE_TTL = 15.0

_CODE_RE = __import__("re").compile(r"^[a-z][a-z0-9_]{1,39}$")


def invalidate_rbac_cache(role_code: Optional[str] = None) -> None:
    if role_code:
        _CACHE.pop(role_code, None)
    else:
        _CACHE.clear()


def ensure_rbac_schema(engine) -> None:
    insp = inspect(engine)
    tables = set(insp.get_table_names())
    with engine.begin() as conn:
        if "roles" in tables:
            cols = {c["name"] for c in insp.get_columns("roles")}
            if "description" not in cols:
                conn.execute(text("ALTER TABLE roles ADD COLUMN description VARCHAR(255)"))
            if "is_system" not in cols:
                conn.execute(text("ALTER TABLE roles ADD COLUMN is_system BOOLEAN DEFAULT TRUE"))
        if "permissions" not in tables:
            conn.execute(
                text(
                    """
                    CREATE TABLE permissions (
                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        code VARCHAR(80) NOT NULL UNIQUE,
                        name VARCHAR(120) NOT NULL,
                        kind VARCHAR(20) NOT NULL,
                        module VARCHAR(40) NOT NULL,
                        sort_order INTEGER DEFAULT 0
                    )
                    """
                )
            )
        if "role_permissions" not in tables:
            conn.execute(
                text(
                    """
                    CREATE TABLE role_permissions (
                        role_id INTEGER NOT NULL,
                        permission_id INTEGER NOT NULL,
                        PRIMARY KEY (role_id, permission_id),
                        FOREIGN KEY(role_id) REFERENCES roles(id) ON DELETE CASCADE,
                        FOREIGN KEY(permission_id) REFERENCES permissions(id) ON DELETE CASCADE
                    )
                    """
                )
            )


def _upsert_permission(db: Session, code: str, name: str, kind: str, module: str, sort_order: int) -> Permission:
    p = db.query(Permission).filter_by(code=code).first()
    if not p:
        p = Permission(code=code, name=name, kind=kind, module=module, sort_order=sort_order)
        db.add(p)
        db.flush()
    else:
        p.name = name
        p.kind = kind
        p.module = module
        p.sort_order = sort_order
    return p


def ensure_permissions_catalog(db: Session) -> dict[str, Permission]:
    by_code: dict[str, Permission] = {}
    for code, name, module, sort_order in MENUS:
        by_code[code] = _upsert_permission(db, code, name, "menu", module, sort_order)
    for code, name, module, sort_order in ACTIONS:
        by_code[code] = _upsert_permission(db, code, name, "action", module, sort_order)
    db.flush()
    return by_code


def ensure_system_roles(db: Session) -> dict[str, Role]:
    """确保四角色存在；mgr→gm；旧 hk/fin 保留行但不再作为主角色。

    角色展示名按 SEED_LOCALE：英文启动写入英文 seed，中文启动保持中文。
    """
    from seed.locale_pack import get_pack, get_seed_locale

    roles: dict[str, Role] = {}
    if get_seed_locale() == "en":
        role_defs = list(getattr(get_pack(), "ROLES", []) or ROLES)
    else:
        role_defs = list(ROLES)
    for code, name, desc in role_defs:
        r = db.query(Role).filter_by(code=code).first()
        if not r:
            r = Role(code=code, name=name, description=desc, is_system=True)
            db.add(r)
            db.flush()
        else:
            r.name = name
            r.description = desc
            r.is_system = True
        roles[code] = r

    # mgr → gm：用户迁移后可选保留 mgr 行做别名查找
    mgr = db.query(Role).filter_by(code="mgr").first()
    if mgr and roles.get("gm"):
        db.query(User).filter(User.role_id == mgr.id).update({User.role_id: roles["gm"].id})

    # 非系统角色统一标记，避免历史 DEFAULT 1 导致无法删除
    for r in db.query(Role).all():
        want = r.code in SYSTEM_ROLE_CODES
        if bool(r.is_system) != want:
            r.is_system = want
    return roles


def apply_default_matrix(db: Session, role_code: str, *, force: bool = False) -> int:
    """为角色写入默认矩阵。force=False 时仅在该角色尚无任何绑定时写入。"""
    role = db.query(Role).filter_by(code=role_code).first()
    if not role:
        return 0
    by_code = ensure_permissions_catalog(db)
    existing = db.query(RolePermission).filter_by(role_id=role.id).count()
    if existing and not force:
        return 0
    db.query(RolePermission).filter_by(role_id=role.id).delete()
    codes = set(DEFAULT_MENUS.get(role_code, [])) | set(DEFAULT_ACTIONS.get(role_code, []))
    n = 0
    for code in codes:
        p = by_code.get(code)
        if not p:
            continue
        db.add(RolePermission(role_id=role.id, permission_id=p.id))
        n += 1
    invalidate_rbac_cache(role_code)
    return n


def bootstrap_rbac(db: Session, *, reset_matrix: bool = False) -> dict:
    ensure_permissions_catalog(db)
    roles = ensure_system_roles(db)
    seeded = {}
    for code in ("admin", "gm", "rm", "fd"):
        seeded[code] = apply_default_matrix(db, code, force=reset_matrix)
    db.commit()
    invalidate_rbac_cache()
    return {"roles": list(roles.keys()), "seeded": seeded}


def set_role_permission_codes(db: Session, role_code: str, codes: Iterable[str]) -> int:
    from domain import NotFoundError

    role = db.query(Role).filter_by(code=role_code).first()
    if not role:
        raise NotFoundError("角色不存在")
    if role_code == "admin":
        # admin 必须保留用户/RBAC
        codes = set(codes) | {"menu.system.users", "menu.system.rbac", "action.system.users", "action.system.rbac"}
    by_code = {p.code: p for p in db.query(Permission).all()}
    db.query(RolePermission).filter_by(role_id=role.id).delete()
    n = 0
    for code in set(codes):
        p = by_code.get(code)
        if not p:
            continue
        db.add(RolePermission(role_id=role.id, permission_id=p.id))
        n += 1
    db.flush()
    invalidate_rbac_cache(role_code)
    return n


def create_custom_role(
    db: Session,
    *,
    code: str,
    name: str,
    description: str = "",
    copy_from: Optional[str] = None,
) -> Role:
    from domain import ConflictError, NotFoundError, ValidationError

    code = (code or "").strip().lower()
    name = (name or "").strip()
    if not _CODE_RE.match(code):
        raise ValidationError("角色编码须为 2–40 位小写字母开头，仅含 a-z / 0-9 / _")
    if code in SYSTEM_ROLE_CODES:
        raise ValidationError("不能占用系统角色编码")
    if not name:
        raise ValidationError("角色名称必填")
    if db.query(Role).filter_by(code=code).first():
        raise ConflictError("角色编码已存在")
    if copy_from:
        src = db.query(Role).filter_by(code=copy_from.strip()).first()
        if not src:
            raise NotFoundError(f"复制来源角色不存在：{copy_from}")
    role = Role(code=code, name=name, description=(description or "").strip() or None, is_system=False)
    db.add(role)
    db.flush()
    if copy_from:
        src_codes = role_codes_snapshot(db, copy_from.strip())
        # 自定义角色不可直接获得用户/RBAC 管理权（除非从 admin 复制时也剥掉）
        blocked = {"menu.system.users", "menu.system.rbac", "action.system.users", "action.system.rbac"}
        src_codes = [c for c in src_codes if c not in blocked]
        set_role_permission_codes(db, code, src_codes)
    else:
        invalidate_rbac_cache(code)
    return role


def update_custom_role(
    db: Session,
    role_code: str,
    *,
    name: Optional[str] = None,
    description: Optional[str] = None,
) -> Role:
    from domain import NotFoundError, ValidationError

    role = db.query(Role).filter_by(code=role_code).first()
    if not role:
        raise NotFoundError("角色不存在")
    if role.code in SYSTEM_ROLE_CODES:
        raise ValidationError("系统角色不可改名")
    if name is not None:
        n = name.strip()
        if not n:
            raise ValidationError("角色名称不能为空")
        role.name = n
    if description is not None:
        role.description = description.strip() or None
    db.flush()
    invalidate_rbac_cache(role_code)
    return role


def delete_custom_role(db: Session, role_code: str) -> None:
    from domain import InvalidStateError, NotFoundError, ValidationError

    role = db.query(Role).filter_by(code=role_code).first()
    if not role:
        raise NotFoundError("角色不存在")
    if role.code in SYSTEM_ROLE_CODES:
        raise ValidationError("系统角色不可删除")
    cnt = db.query(User).filter(User.role_id == role.id).count()
    if cnt:
        raise InvalidStateError(f"仍有 {cnt} 个账号使用该角色，请先调整账号角色后再删")
    db.query(RolePermission).filter_by(role_id=role.id).delete()
    db.delete(role)
    db.flush()
    invalidate_rbac_cache(role_code)


def list_all_roles(db: Session) -> list[Role]:
    """系统角色在前，自定义角色按 id。"""
    ensure_system_roles(db)
    rows = db.query(Role).order_by(Role.id.asc()).all()
    order = {c: i for i, (c, *_rest) in enumerate(ROLES)}

    def _key(r: Role):
        if r.code in order:
            return (0, order[r.code])
        return (1, r.id)

    return sorted(rows, key=_key)


def _load_codes_uncached(db: Session, role_code: str) -> tuple[frozenset[str], frozenset[str]]:
    if role_code == "admin":
        # 超管：目录全量（即使矩阵被误改，运行时仍全开）
        menus = frozenset(c for c, *_ in MENUS)
        actions = frozenset(c for c, *_ in ACTIONS)
        return menus, actions
    role = db.query(Role).filter_by(code=role_code).first()
    if not role:
        return frozenset(), frozenset()
    rows = (
        db.query(Permission)
        .join(RolePermission, RolePermission.permission_id == Permission.id)
        .filter(RolePermission.role_id == role.id)
        .all()
    )
    menus = frozenset(p.code for p in rows if p.kind == "menu")
    actions = frozenset(p.code for p in rows if p.kind == "action")
    return menus, actions


def get_role_permission_sets(db: Session, role_code: str) -> tuple[frozenset[str], frozenset[str]]:
    now = time.time()
    hit = _CACHE.get(role_code)
    if hit and now - hit[2] < _CACHE_TTL:
        return hit[0], hit[1]
    menus, actions = _load_codes_uncached(db, role_code)
    hidden = set()
    try:
        from infra.packs import pack_menus_hidden

        hidden = set(pack_menus_hidden())
    except Exception:
        hidden = set()
    if hidden:
        menus = frozenset(m for m in menus if m not in hidden)
        actions = frozenset(a for a in actions if a not in hidden)
    _CACHE[role_code] = (menus, actions, now)
    return menus, actions


def role_has_scope(db: Session, role_code: str, *need: str) -> bool:
    if not need:
        return True
    if role_code == "admin":
        return True
    menus, actions = get_role_permission_sets(db, role_code)
    have = menus | actions
    return all(n in have for n in need)


def permission_tree(db: Session) -> list[dict]:
    from infra.i18n import t as _t

    ensure_permissions_catalog(db)
    perms = db.query(Permission).order_by(Permission.module, Permission.kind, Permission.sort_order).all()
    by_mod: dict[str, dict] = {}
    for p in perms:
        bucket = by_mod.setdefault(
            p.module,
            {
                "module": p.module,
                "label": _t(MODULE_LABELS.get(p.module, p.module)),
                "menus": [],
                "actions": [],
            },
        )
        item = {"code": p.code, "name": _t(p.name), "kind": p.kind}
        if p.kind == "menu":
            try:
                from infra.packs import pack_menus_hidden

                if p.code in pack_menus_hidden():
                    continue
            except Exception:
                pass
            bucket["menus"].append(item)
        else:
            bucket["actions"].append(item)
    order = list(MODULE_LABELS.keys())
    return sorted(by_mod.values(), key=lambda x: order.index(x["module"]) if x["module"] in order else 99)


def role_codes_snapshot(db: Session, role_code: str) -> list[str]:
    menus, actions = get_role_permission_sets(db, role_code)
    return sorted(menus | actions)


# ---- 对外 DTO / 用户管理（供 facade 编排）----


def get_role_or_raise(db: Session, code: str) -> Role:
    from domain import NotFoundError

    r = db.query(Role).filter_by(code=code).first()
    if not r:
        raise NotFoundError(f"角色不存在：{code}")
    return r


def role_public_dict(db: Session, r: Role) -> dict:
    from infra.i18n import t as _t

    return {
        "id": r.id,
        "code": r.code,
        "name": _t(r.name or ""),
        "description": _t(r.description or "") if r.description else "",
        "is_system": r.code in SYSTEM_ROLE_CODES,
        "permission_count": len(role_codes_snapshot(db, r.code)),
        "user_count": db.query(User).filter(User.role_id == r.id).count(),
    }


def user_public_dict(u: User, role: Optional[Role]) -> dict:
    from api_common import row_to_dict
    from infra.i18n import t as _t

    d = row_to_dict(u)
    d.pop("password_hash", None)
    d["role_code"] = role.code if role else ""
    d["role_name"] = _t(role.name) if role and role.name else ""
    if d.get("full_name"):
        d["full_name"] = _t(str(d["full_name"]))
    return d


def list_roles_enriched(db: Session) -> list[dict]:
    return [role_public_dict(db, r) for r in list_all_roles(db)]


def list_users_enriched(db: Session) -> list[dict]:
    users = db.query(User).order_by(User.id.asc()).all()
    role_map = {r.id: r for r in db.query(Role).all()}
    return [user_public_dict(u, role_map.get(u.role_id)) for u in users]


def reset_role_defaults(db: Session, role_code: str) -> dict:
    """系统角色恢复默认矩阵；自定义角色清空权限。"""
    role = get_role_or_raise(db, role_code)
    if role.code in SYSTEM_ROLE_CODES:
        n = apply_default_matrix(db, role_code, force=True)
    else:
        n = set_role_permission_codes(db, role_code, [])
    db.flush()
    return {"role_code": role_code, "restored": n, "codes": role_codes_snapshot(db, role_code)}


def create_user_account(
    db: Session,
    *,
    hotel_id: int,
    username: str,
    password: str,
    role_code: str,
    full_name: str = "",
    phone: str = "",
    is_active: bool = True,
    actor_role: str = "",
) -> dict:
    from domain import AuthorizationError, ConflictError, ValidationError
    from infra.auth_local import hash_password
    from models import Hotel

    username = (username or "").strip()
    if not username or not password:
        raise ValidationError("用户名与密码必填")
    if db.query(User).filter_by(username=username).first():
        raise ConflictError("用户名已存在")
    role_code = (role_code or "").strip()
    if role_code == "admin" and actor_role != "admin":
        raise AuthorizationError("仅系统管理员可创建管理员账号")
    role = get_role_or_raise(db, role_code)
    hotel = db.get(Hotel, hotel_id) or db.query(Hotel).order_by(Hotel.id).first()
    u = User(
        hotel_id=hotel.id if hotel else hotel_id,
        role_id=role.id,
        username=username,
        password_hash=hash_password(password),
        full_name=(full_name or username).strip(),
        phone=(phone or "").strip() or None,
        is_active=bool(is_active),
    )
    db.add(u)
    db.flush()
    db.refresh(u)
    return user_public_dict(u, role)


def update_user_account(
    db: Session,
    user_id: int,
    *,
    actor_role: str = "",
    actor_user_id: Optional[int] = None,
    full_name: Optional[str] = None,
    role_code: Optional[str] = None,
    phone: Optional[str] = None,
    is_active: Optional[bool] = None,
    password: Optional[str] = None,
) -> dict:
    from domain import AuthorizationError, NotFoundError, ValidationError
    from infra.auth_local import hash_password

    u = db.get(User, user_id)
    if not u:
        raise NotFoundError("用户不存在")
    if role_code is not None:
        rc = role_code.strip()
        if rc == "admin" and actor_role != "admin":
            raise AuthorizationError("仅系统管理员可分配管理员角色")
        if u.username == "admin" and rc != "admin":
            raise ValidationError("内置 admin 账号不可更改角色")
        u.role_id = get_role_or_raise(db, rc).id
    if full_name is not None:
        u.full_name = full_name.strip() or u.full_name
    if phone is not None:
        u.phone = phone.strip() or None
    if is_active is not None:
        if u.username == "admin" and not is_active:
            raise ValidationError("内置 admin 账号不可停用")
        if actor_user_id is not None and u.id == actor_user_id and not is_active:
            raise ValidationError("不能停用当前登录账号")
        u.is_active = bool(is_active)
    if password:
        u.password_hash = hash_password(password)
    db.flush()
    db.refresh(u)
    role = db.get(Role, u.role_id) if u.role_id else None
    return user_public_dict(u, role)
