# SPDX-License-Identifier: Apache-2.0
"""auto-generated facade module for analytics domain.

Auto-generated by gen_facades.py on demand. Do not edit by hand.

职责：
  - 调 service 函数 + 透传 BusinessError
  - 未来扩展：参数校验、事务边界、跨 service 编排
"""

from __future__ import annotations

# 业务异常（透传用）
from domain import (  # noqa: F401
    AuthorizationError,
    BusinessError,
    ConflictError,
    InvalidStateError,
    NotFoundError,
    ValidationError,
)
from infra.commercial_pack import bind as _cbind

_ack_pii = _cbind("commercial.analytics.ai_ask_service", "ack_pii")
_apply_clarify_choice = _cbind("commercial.analytics.ai_ask_service", "apply_clarify_choice")
_catalog_payload = _cbind("commercial.analytics.ai_ask_service", "catalog_payload")
_confirm_and_execute = _cbind("commercial.analytics.ai_ask_service", "confirm_and_execute")
_route_question = _cbind("commercial.analytics.ai_ask_service", "route_question")
_stream_confirm_and_execute = _cbind("commercial.analytics.ai_ask_service", "stream_confirm_and_execute")

_build_analytics_context = _cbind("commercial.analytics.analytics_ai", "build_analytics_context")
_execute_analytics_action = _cbind("commercial.analytics.analytics_ai", "execute_analytics_action")
_generate_analytics_actions = _cbind("commercial.analytics.analytics_ai", "generate_analytics_actions")
_narrate_attribution_insight = _cbind("commercial.analytics.analytics_ai", "narrate_attribution_insight")
_narrate_channel_insight = _cbind("commercial.analytics.analytics_ai", "narrate_channel_insight")

_generate_ask_data = _cbind("commercial.analytics.ask_data_service", "generate_ask_data")
_stream_ask_data = _cbind("commercial.analytics.ask_data_service", "stream_ask_data")

_execute_board_ai_action = _cbind("commercial.analytics.board_ai", "execute_board_ai_action")
_narrate_board_ai = _cbind("commercial.analytics.board_ai", "narrate_board_ai")

from analytics.dashboard_service import (
    build_realtime_snapshot as _build_realtime_snapshot,
)
from analytics.forecast_service import (
    build_revenue_forecast as _build_revenue_forecast,
)
from analytics.insight_service import (
    build_workspace as _build_workspace,
)
from analytics.insight_service import (
    chat_reply as _chat_reply,
)
from analytics.insight_service import (
    run_ask as _run_ask,
)
from analytics.insight_service import (
    stream_ask as _stream_ask,
)


def ack_pii(*args, **kwargs):
    """薄包装 — 调 analytics.ai_ask_service.ack_pii。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _ack_pii(*args, **kwargs)


def apply_clarify_choice(*args, **kwargs):
    """薄包装 — 调 analytics.ai_ask_service.apply_clarify_choice。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _apply_clarify_choice(*args, **kwargs)


def catalog_payload(*args, **kwargs):
    """薄包装 — 调 analytics.ai_ask_service.catalog_payload。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _catalog_payload(*args, **kwargs)


def confirm_and_execute(*args, **kwargs):
    """薄包装 — 调 analytics.ai_ask_service.confirm_and_execute。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _confirm_and_execute(*args, **kwargs)


def route_question(*args, **kwargs):
    """薄包装 — 调 analytics.ai_ask_service.route_question。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _route_question(*args, **kwargs)


def stream_confirm_and_execute(*args, **kwargs):
    """薄包装 — 调 analytics.ai_ask_service.stream_confirm_and_execute。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _stream_confirm_and_execute(*args, **kwargs)


def build_analytics_context(*args, **kwargs):
    """薄包装 — 调 analytics.analytics_ai.build_analytics_context。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _build_analytics_context(*args, **kwargs)


def execute_analytics_action(*args, **kwargs):
    """薄包装 — 调 analytics.analytics_ai.execute_analytics_action。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _execute_analytics_action(*args, **kwargs)


def generate_analytics_actions(*args, **kwargs):
    """薄包装 — 调 analytics.analytics_ai.generate_analytics_actions。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _generate_analytics_actions(*args, **kwargs)


def narrate_attribution_insight(*args, **kwargs):
    """薄包装 — 调 analytics.analytics_ai.narrate_attribution_insight。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _narrate_attribution_insight(*args, **kwargs)


def narrate_channel_insight(*args, **kwargs):
    """薄包装 — 调 analytics.analytics_ai.narrate_channel_insight。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _narrate_channel_insight(*args, **kwargs)


def generate_ask_data(*args, **kwargs):
    """薄包装 — 调 analytics.ask_data_service.generate_ask_data。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _generate_ask_data(*args, **kwargs)


def stream_ask_data(*args, **kwargs):
    """薄包装 — 调 analytics.ask_data_service.stream_ask_data。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _stream_ask_data(*args, **kwargs)


def execute_board_ai_action(*args, **kwargs):
    """薄包装 — 调 analytics.board_ai.execute_board_ai_action。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _execute_board_ai_action(*args, **kwargs)


def build_realtime_snapshot(*args, **kwargs):
    """薄包装 — 调 analytics.dashboard_service.build_realtime_snapshot。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _build_realtime_snapshot(*args, **kwargs)


def build_revenue_forecast(*args, **kwargs):
    """薄包装 — 调 analytics.forecast_service.build_revenue_forecast。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _build_revenue_forecast(*args, **kwargs)


def build_workspace(*args, **kwargs):
    """薄包装 — 调 analytics.insight_service.build_workspace。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _build_workspace(*args, **kwargs)


def chat_reply(*args, **kwargs):
    """薄包装 — 调 analytics.insight_service.chat_reply。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _chat_reply(*args, **kwargs)


def run_ask(*args, **kwargs):
    """薄包装 — 调 analytics.insight_service.run_ask。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _run_ask(*args, **kwargs)


def stream_ask(*args, **kwargs):
    """薄包装 — 调 analytics.insight_service.stream_ask。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _stream_ask(*args, **kwargs)


def narrate_board_ai(db, hotel_id, kind, payload=None):
    from infra.commercial_pack import load_module, unavailable_error

    mod = load_module("commercial.analytics.board_ai")
    if mod is None:
        raise unavailable_error()
    if kind not in getattr(mod, "NARRATIVE_KINDS", ()):
        raise NotFoundError(f"未知 AI 能力: {kind}")
    return _narrate_board_ai(db, hotel_id, kind, payload or {})


def list_ai_commands(db, hotel_id):
    from api_common import row_to_dict
    from models import AiCommand

    rows = db.query(AiCommand).filter(AiCommand.hotel_id == hotel_id).all()
    return [row_to_dict(c) for c in rows]
