# SPDX-License-Identifier: Apache-2.0
"""auto-generated facade module for mkt domain.

Auto-generated by gen_facades.py on demand. Do not edit by hand.

职责：
  - 调 service 函数 + 透传 BusinessError
  - 未来扩展：参数校验、事务边界、跨 service 编排
"""

from __future__ import annotations

# 业务异常（透传用）
from domain import (  # noqa: F401
    AuthorizationError,
    BusinessError,
    ConflictError,
    InvalidStateError,
    NotFoundError,
    ValidationError,
)
from infra.commercial_pack import bind as _cbind
from mkt.acquisition_service import (
    build_acquisition_board as _build_acquisition_board,
)
from mkt.acquisition_service import (
    build_acquisition_douyin_trade_board as _build_acquisition_douyin_trade_board,
)
from mkt.acquisition_service import (
    build_acquisition_roi as _build_acquisition_roi,
)
from mkt.acquisition_service import (
    claim_acquisition_lead as _claim_acquisition_lead,
)
from mkt.acquisition_service import (
    convert_acquisition_booking as _convert_acquisition_booking,
)
from mkt.acquisition_service import (
    create_acquisition_channel_binding as _create_acquisition_channel_binding,
)
from mkt.acquisition_service import (
    create_manual_acquisition_lead as _create_manual_acquisition_lead,
)
from mkt.acquisition_service import (
    list_acquisition_channel_bindings as _list_acquisition_channel_bindings,
)
from mkt.acquisition_service import (
    list_acquisition_leads as _list_acquisition_leads,
)
from mkt.acquisition_service import (
    list_acquisition_webhook_events as _list_acquisition_webhook_events,
)
from mkt.acquisition_service import (
    mark_acquisition_arrived as _mark_acquisition_arrived,
)
from mkt.acquisition_service import (
    mock_ingest_acquisition as _mock_ingest_acquisition,
)
from mkt.acquisition_service import (
    simulate_acquisition_webhook as _simulate_acquisition_webhook,
)
from mkt.acquisition_service import (
    update_acquisition_channel_binding as _update_acquisition_channel_binding,
)
from mkt.mkt_auto_grant import (
    delete_rule as _auto_grant_delete_rule,
)
from mkt.mkt_auto_grant import (
    list_rules as _auto_grant_list_rules,
)
from mkt.mkt_auto_grant import (
    list_templates as _auto_grant_list_templates,
)
from mkt.mkt_auto_grant import (
    preview_audience as _auto_grant_preview_audience,
)
from mkt.mkt_auto_grant import (
    run_rule_scan as _auto_grant_run_rule_scan,
)
from mkt.mkt_auto_grant import (
    set_rule_enabled as _auto_grant_set_rule_enabled,
)
from mkt.mkt_auto_grant import (
    try_run_for_guest as _auto_grant_try_run_for_guest,
)
from mkt.mkt_auto_grant import (
    upsert_rule as _auto_grant_upsert_rule,
)
from mkt.mkt_auto_rules import (
    delete_rule as _auto_rules_delete_rule,
)
from mkt.mkt_auto_rules import (
    dry_run as _auto_rules_dry_run,
)
from mkt.mkt_auto_rules import (
    get_rule as _auto_rules_get_rule,
)
from mkt.mkt_auto_rules import (
    kpi_summary as _auto_rules_kpi_summary,
)
from mkt.mkt_auto_rules import (
    list_event_types as _auto_rules_list_event_types,
)
from mkt.mkt_auto_rules import (
    list_field_catalog as _auto_rules_list_field_catalog,
)
from mkt.mkt_auto_rules import (
    list_rules as _auto_rules_list_rules,
)
from mkt.mkt_auto_rules import (
    list_triggers as _auto_rules_list_triggers,
)
from mkt.mkt_auto_rules import (
    preview_estimate as _auto_rules_preview_estimate,
)
from mkt.mkt_auto_rules import (
    run_rule_scan as _auto_rules_run_rule_scan,
)
from mkt.mkt_auto_rules import (
    set_status as _auto_rules_set_status,
)
from mkt.mkt_auto_rules import (
    upsert_rule as _auto_rules_upsert_rule,
)

_execute_coupon_ai_action = _cbind("commercial.mkt.mkt_coupon_ai", "execute_coupon_ai_action")

from mkt.mkt_coupon_engine import (
    claim_instance as _claim_instance,
)
from mkt.mkt_coupon_engine import (
    expire_due_instances as _expire_due_instances,
)
from mkt.mkt_coupon_engine import (
    fire_event as _fire_event,
)
from mkt.mkt_coupon_engine import (
    list_redeem_log as _list_redeem_log,
)
from mkt.mkt_coupon_engine import (
    redeem_instance as _redeem_instance,
)
from mkt.mkt_coupon_engine import (
    verify_instance_preview as _verify_instance_preview,
)
from mkt.mkt_coupon_engine import (
    wallet_by_customer as _wallet_by_customer,
)

_execute_member_ai_action = _cbind("commercial.mkt.mkt_member_ai", "execute_member_ai_action")

from mkt.mkt_member_system import (
    delete_level as _delete_level,
)
from mkt.mkt_member_system import (
    delete_recharge_tier as _delete_recharge_tier,
)
from mkt.mkt_member_system import (
    get_benefits as _get_benefits,
)
from mkt.mkt_member_system import (
    get_level_rule as _get_level_rule,
)
from mkt.mkt_member_system import (
    get_point_rule as _get_point_rule,
)
from mkt.mkt_member_system import (
    list_levels as _list_levels,
)
from mkt.mkt_member_system import (
    list_recharge_tiers as _list_recharge_tiers,
)
from mkt.mkt_member_system import (
    member_system_bundle as _member_system_bundle,
)
from mkt.mkt_member_system import (
    preview_points as _preview_points,
)
from mkt.mkt_member_system import (
    put_benefits as _put_benefits,
)
from mkt.mkt_member_system import (
    save_level_rule as _save_level_rule,
)
from mkt.mkt_member_system import (
    save_point_rule as _save_point_rule,
)
from mkt.mkt_member_system import (
    upsert_level as _upsert_level,
)
from mkt.mkt_member_system import (
    upsert_recharge_tier as _upsert_recharge_tier,
)

_execute_points_ai_action = _cbind("commercial.mkt.mkt_points_ai", "execute_points_ai_action")

_execute_mkt_diagnosis_action = _cbind("commercial.mkt.mkt_private_ai", "execute_mkt_diagnosis_action")
_narrate_mkt_ai = _cbind("commercial.mkt.mkt_private_ai", "narrate_mkt_ai")

from mkt.mkt_private_overview import (
    private_overview as _private_overview,
)
from mkt.mkt_rule_engine import (
    list_field_catalog as _grant_field_catalog,
)
from mkt.mkt_service import (
    add_customer_note as _add_customer_note,
)
from mkt.mkt_service import (
    approve_campaign as _approve_campaign,
)
from mkt.mkt_service import (
    bind_coupon_to_claim_landing as _bind_coupon_to_claim_landing,
)
from mkt.mkt_service import (
    create_campaign as _create_campaign,
)
from mkt.mkt_service import (
    create_coupon as _create_coupon,
)
from mkt.mkt_service import (
    create_landing_page as _create_landing_page,
)
from mkt.mkt_service import (
    delete_automation as _delete_automation,
)
from mkt.mkt_service import (
    get_mkt_customer as _get_mkt_customer,
)
from mkt.mkt_service import (
    get_mkt_settings as _get_mkt_settings,
)
from mkt.mkt_service import (
    grant_coupon as _grant_coupon,
)
from mkt.mkt_service import (
    list_automations as _list_automations,
)
from mkt.mkt_service import (
    list_campaign_templates as _list_campaign_templates,
)
from mkt.mkt_service import (
    list_campaigns as _list_campaigns,
)
from mkt.mkt_service import (
    list_claim_landing_options as _list_claim_landing_options,
)
from mkt.mkt_service import (
    list_coupon_guest_ownership as _list_coupon_guest_ownership,
)
from mkt.mkt_service import (
    list_coupon_templates as _list_coupon_templates,
)
from mkt.mkt_service import (
    list_coupons as _list_coupons,
)
from mkt.mkt_service import (
    list_grant_segments as _list_grant_segments,
)
from mkt.mkt_service import (
    list_grants as _list_grants,
)
from mkt.mkt_service import (
    list_landing_pages as _list_landing_pages,
)
from mkt.mkt_service import (
    list_landing_templates as _list_landing_templates,
)
from mkt.mkt_service import (
    list_mkt_customers as _list_mkt_customers,
)
from mkt.mkt_service import (
    patch_campaign_status as _patch_campaign_status,
)
from mkt.mkt_service import (
    preview_automation as _preview_automation,
)
from mkt.mkt_service import (
    preview_grant_audience as _preview_grant_audience,
)
from mkt.mkt_service import (
    preview_landing_html as _preview_landing_html,
)
from mkt.mkt_service import (
    public_claim_without_token as _public_claim_without_token,
)
from mkt.mkt_service import (
    publish_landing_page as _publish_landing_page,
)
from mkt.mkt_service import (
    reject_campaign as _reject_campaign,
)
from mkt.mkt_service import (
    save_mkt_settings as _save_mkt_settings,
)
from mkt.mkt_service import (
    set_automation_enabled as _set_automation_enabled,
)
from mkt.mkt_service import (
    unpublish_landing_page as _unpublish_landing_page,
)
from mkt.mkt_service import (
    update_coupon_batch as _update_coupon_batch,
)
from mkt.mkt_service import (
    update_coupon_status as _update_coupon_status,
)
from mkt.mkt_service import (
    update_landing_page as _update_landing_page,
)
from mkt.mkt_service import (
    upsert_automation as _upsert_automation,
)
from mkt.mkt_service import (
    verify_coupon as _verify_coupon,
)

_resolve_filter_spec = _cbind("commercial.mkt.segment_nl_intent", "resolve_filter_spec")
_stream_nl_segment_query = _cbind("commercial.mkt.segment_nl_intent", "stream_nl_segment_query")

from mkt.wallet_service import (
    lookup_coupon_by_code,
)
from mkt.wallet_service import (
    redeem_guest_coupon as _redeem_guest_coupon,
)


def build_acquisition_board(*args, **kwargs):
    """薄包装 — 调 mkt.acquisition_service.build_acquisition_board。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _build_acquisition_board(*args, **kwargs)


def build_acquisition_douyin_trade_board(*args, **kwargs):
    """薄包装 — 调 mkt.acquisition_service.build_acquisition_douyin_trade_board。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _build_acquisition_douyin_trade_board(*args, **kwargs)


def build_acquisition_roi(*args, **kwargs):
    """薄包装 — 调 mkt.acquisition_service.build_acquisition_roi。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _build_acquisition_roi(*args, **kwargs)


def claim_acquisition_lead(*args, **kwargs):
    """薄包装 — 调 mkt.acquisition_service.claim_acquisition_lead。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _claim_acquisition_lead(*args, **kwargs)


def convert_acquisition_booking(*args, **kwargs):
    """薄包装 — 调 mkt.acquisition_service.convert_acquisition_booking。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _convert_acquisition_booking(*args, **kwargs)


def create_acquisition_channel_binding(*args, **kwargs):
    """薄包装 — 调 mkt.acquisition_service.create_acquisition_channel_binding。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _create_acquisition_channel_binding(*args, **kwargs)


def create_manual_acquisition_lead(*args, **kwargs):
    """薄包装 — 调 mkt.acquisition_service.create_manual_acquisition_lead。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _create_manual_acquisition_lead(*args, **kwargs)


def list_acquisition_channel_bindings(*args, **kwargs):
    """薄包装 — 调 mkt.acquisition_service.list_acquisition_channel_bindings。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _list_acquisition_channel_bindings(*args, **kwargs)


def list_acquisition_leads(*args, **kwargs):
    """薄包装 — 调 mkt.acquisition_service.list_acquisition_leads。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _list_acquisition_leads(*args, **kwargs)


def list_acquisition_webhook_events(*args, **kwargs):
    """薄包装 — 调 mkt.acquisition_service.list_acquisition_webhook_events。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _list_acquisition_webhook_events(*args, **kwargs)


def mark_acquisition_arrived(*args, **kwargs):
    """薄包装 — 调 mkt.acquisition_service.mark_acquisition_arrived。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _mark_acquisition_arrived(*args, **kwargs)


def mock_ingest_acquisition(*args, **kwargs):
    """薄包装 — 调 mkt.acquisition_service.mock_ingest_acquisition。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _mock_ingest_acquisition(*args, **kwargs)


def simulate_acquisition_webhook(*args, **kwargs):
    """薄包装 — 调 mkt.acquisition_service.simulate_acquisition_webhook。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _simulate_acquisition_webhook(*args, **kwargs)


def update_acquisition_channel_binding(*args, **kwargs):
    """薄包装 — 调 mkt.acquisition_service.update_acquisition_channel_binding。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _update_acquisition_channel_binding(*args, **kwargs)


# ---- auto-grant（产品层自动发券）----
def list_auto_grant_templates(*args, **kwargs):
    return _auto_grant_list_templates(*args, **kwargs)


def preview_auto_grant_audience(*args, **kwargs):
    return _auto_grant_preview_audience(*args, **kwargs)


def list_auto_grant_rules(*args, **kwargs):
    return _auto_grant_list_rules(*args, **kwargs)


def upsert_auto_grant_rule(*args, **kwargs):
    return _auto_grant_upsert_rule(*args, **kwargs)


def set_auto_grant_rule_enabled(*args, **kwargs):
    return _auto_grant_set_rule_enabled(*args, **kwargs)


def delete_auto_grant_rule(*args, **kwargs):
    return _auto_grant_delete_rule(*args, **kwargs)


def run_auto_grant_scan(*args, **kwargs):
    return _auto_grant_run_rule_scan(*args, **kwargs)


def try_auto_grant_for_guest(*args, **kwargs):
    return _auto_grant_try_run_for_guest(*args, **kwargs)


def list_auto_grant_fields(*args, **kwargs):
    """auto-grant 字段目录来自 rule_engine。"""
    return _grant_field_catalog(*args, **kwargs)


# ---- auto-rules（四表权威稿）----
def delete_auto_rule(*args, **kwargs):
    return _auto_rules_delete_rule(*args, **kwargs)


def dry_run(*args, **kwargs):
    return _auto_rules_dry_run(*args, **kwargs)


def get_auto_rule(*args, **kwargs):
    return _auto_rules_get_rule(*args, **kwargs)


def kpi_summary(*args, **kwargs):
    return _auto_rules_kpi_summary(*args, **kwargs)


def list_event_types(*args, **kwargs):
    return _auto_rules_list_event_types(*args, **kwargs)


def list_auto_rules_fields(*args, **kwargs):
    return _auto_rules_list_field_catalog(*args, **kwargs)


def list_auto_rules(*args, **kwargs):
    return _auto_rules_list_rules(*args, **kwargs)


def list_triggers(*args, **kwargs):
    return _auto_rules_list_triggers(*args, **kwargs)


def preview_estimate(*args, **kwargs):
    return _auto_rules_preview_estimate(*args, **kwargs)


def run_auto_rules_scan(*args, **kwargs):
    return _auto_rules_run_rule_scan(*args, **kwargs)


def set_status(*args, **kwargs):
    return _auto_rules_set_status(*args, **kwargs)


def upsert_auto_rule(*args, **kwargs):
    return _auto_rules_upsert_rule(*args, **kwargs)


# 兼容旧名（明确指向 auto-rules；auto-grant 请用 list_auto_grant_*）
def delete_rule(*args, **kwargs):
    return delete_auto_rule(*args, **kwargs)


def list_rules(*args, **kwargs):
    return list_auto_rules(*args, **kwargs)


def upsert_rule(*args, **kwargs):
    return upsert_auto_rule(*args, **kwargs)


def run_rule_scan(*args, **kwargs):
    return run_auto_rules_scan(*args, **kwargs)


def get_rule(*args, **kwargs):
    return get_auto_rule(*args, **kwargs)


def list_field_catalog(*args, **kwargs):
    """默认返回 auto-rules 字段目录；auto-grant 请用 list_auto_grant_fields。"""
    return list_auto_rules_fields(*args, **kwargs)


def list_templates(*args, **kwargs):
    return list_auto_grant_templates(*args, **kwargs)


def preview_audience(*args, **kwargs):
    return preview_auto_grant_audience(*args, **kwargs)


def set_rule_enabled(*args, **kwargs):
    return set_auto_grant_rule_enabled(*args, **kwargs)


def try_run_for_guest(*args, **kwargs):
    return try_auto_grant_for_guest(*args, **kwargs)


def execute_coupon_ai_action(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_coupon_ai.execute_coupon_ai_action。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _execute_coupon_ai_action(*args, **kwargs)


def claim_instance(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_coupon_engine.claim_instance。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _claim_instance(*args, **kwargs)


def expire_due_instances(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_coupon_engine.expire_due_instances。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _expire_due_instances(*args, **kwargs)


def fire_event(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_coupon_engine.fire_event。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _fire_event(*args, **kwargs)


def list_redeem_log(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_coupon_engine.list_redeem_log。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _list_redeem_log(*args, **kwargs)


def redeem_instance(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_coupon_engine.redeem_instance。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _redeem_instance(*args, **kwargs)


def verify_instance_preview(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_coupon_engine.verify_instance_preview。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _verify_instance_preview(*args, **kwargs)


def wallet_by_customer(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_coupon_engine.wallet_by_customer。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _wallet_by_customer(*args, **kwargs)


def execute_member_ai_action(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_member_ai.execute_member_ai_action。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _execute_member_ai_action(*args, **kwargs)


def delete_level(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_member_system.delete_level。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _delete_level(*args, **kwargs)


def delete_recharge_tier(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_member_system.delete_recharge_tier。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _delete_recharge_tier(*args, **kwargs)


def get_benefits(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_member_system.get_benefits。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _get_benefits(*args, **kwargs)


def get_level_rule(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_member_system.get_level_rule。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _get_level_rule(*args, **kwargs)


def get_point_rule(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_member_system.get_point_rule。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _get_point_rule(*args, **kwargs)


def list_levels(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_member_system.list_levels。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _list_levels(*args, **kwargs)


def list_recharge_tiers(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_member_system.list_recharge_tiers。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _list_recharge_tiers(*args, **kwargs)


def member_system_bundle(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_member_system.member_system_bundle。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _member_system_bundle(*args, **kwargs)


def preview_points(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_member_system.preview_points。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _preview_points(*args, **kwargs)


def put_benefits(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_member_system.put_benefits。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _put_benefits(*args, **kwargs)


def save_level_rule(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_member_system.save_level_rule。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _save_level_rule(*args, **kwargs)


def save_point_rule(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_member_system.save_point_rule。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _save_point_rule(*args, **kwargs)


def upsert_level(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_member_system.upsert_level。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _upsert_level(*args, **kwargs)


def upsert_recharge_tier(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_member_system.upsert_recharge_tier。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _upsert_recharge_tier(*args, **kwargs)


def execute_points_ai_action(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_points_ai.execute_points_ai_action。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _execute_points_ai_action(*args, **kwargs)


def _narrate_commercial_kind(dotted: str, fn_name: str, db, hotel_id, kind, payload=None):
    from infra.commercial_pack import load_module, unavailable_error

    mod = load_module(dotted)
    if mod is None:
        raise unavailable_error()
    if kind not in getattr(mod, "NARRATIVE_KINDS", ()):
        raise NotFoundError(f"未知 AI 能力: {kind}")
    return getattr(mod, fn_name)(db, hotel_id, kind, payload or {})


def narrate_points_ai(db, hotel_id, kind, payload=None):
    return _narrate_commercial_kind("commercial.mkt.mkt_points_ai", "narrate_points_ai", db, hotel_id, kind, payload)


def narrate_member_ai(db, hotel_id, kind, payload=None):
    return _narrate_commercial_kind("commercial.mkt.mkt_member_ai", "narrate_member_ai", db, hotel_id, kind, payload)


def narrate_coupon_ai(db, hotel_id, kind, payload=None):
    return _narrate_commercial_kind("commercial.mkt.mkt_coupon_ai", "narrate_coupon_ai", db, hotel_id, kind, payload)


def stream_mkt_ai_ops(db, hotel_id, kind):
    from infra.commercial_pack import load_module, unavailable_error

    mod = load_module("commercial.mkt.mkt_private_ai")
    if mod is None:
        raise unavailable_error()
    if kind not in getattr(mod, "NARRATIVE_KINDS", ()):
        raise NotFoundError(f"未知 AI 能力: {kind}")
    yield from mod.stream_mkt_ai_ops(db, hotel_id, kind)


def execute_mkt_diagnosis_action(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_private_ai.execute_mkt_diagnosis_action。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _execute_mkt_diagnosis_action(*args, **kwargs)


def narrate_mkt_ai(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_private_ai.narrate_mkt_ai。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _narrate_mkt_ai(*args, **kwargs)


def private_overview(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_private_overview.private_overview。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _private_overview(*args, **kwargs)


def add_customer_note(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_service.add_customer_note。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _add_customer_note(*args, **kwargs)


def approve_campaign(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_service.approve_campaign。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _approve_campaign(*args, **kwargs)


def bind_coupon_to_claim_landing(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_service.bind_coupon_to_claim_landing。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _bind_coupon_to_claim_landing(*args, **kwargs)


def create_campaign(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_service.create_campaign。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _create_campaign(*args, **kwargs)


def create_coupon(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_service.create_coupon。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _create_coupon(*args, **kwargs)


def create_landing_page(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_service.create_landing_page。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _create_landing_page(*args, **kwargs)


def delete_automation(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_service.delete_automation。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _delete_automation(*args, **kwargs)


def get_mkt_customer(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_service.get_mkt_customer。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _get_mkt_customer(*args, **kwargs)


def get_mkt_settings(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_service.get_mkt_settings。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _get_mkt_settings(*args, **kwargs)


def grant_coupon(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_service.grant_coupon。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _grant_coupon(*args, **kwargs)


def list_automations(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_service.list_automations。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _list_automations(*args, **kwargs)


def list_campaign_templates(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_service.list_campaign_templates。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _list_campaign_templates(*args, **kwargs)


def list_campaigns(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_service.list_campaigns。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _list_campaigns(*args, **kwargs)


def list_claim_landing_options(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_service.list_claim_landing_options。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _list_claim_landing_options(*args, **kwargs)


def list_coupon_guest_ownership(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_service.list_coupon_guest_ownership。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _list_coupon_guest_ownership(*args, **kwargs)


def list_coupon_templates(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_service.list_coupon_templates。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _list_coupon_templates(*args, **kwargs)


def list_coupons(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_service.list_coupons。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _list_coupons(*args, **kwargs)


def list_grant_segments(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_service.list_grant_segments。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _list_grant_segments(*args, **kwargs)


def list_grants(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_service.list_grants。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _list_grants(*args, **kwargs)


def list_landing_pages(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_service.list_landing_pages。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _list_landing_pages(*args, **kwargs)


def list_landing_templates(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_service.list_landing_templates。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _list_landing_templates(*args, **kwargs)


def list_mkt_customers(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_service.list_mkt_customers。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _list_mkt_customers(*args, **kwargs)


def patch_campaign_status(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_service.patch_campaign_status。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _patch_campaign_status(*args, **kwargs)


def preview_automation(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_service.preview_automation。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _preview_automation(*args, **kwargs)


def preview_grant_audience(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_service.preview_grant_audience。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _preview_grant_audience(*args, **kwargs)


def preview_landing_html(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_service.preview_landing_html。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _preview_landing_html(*args, **kwargs)


def public_claim_without_token(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_service.public_claim_without_token。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _public_claim_without_token(*args, **kwargs)


def publish_landing_page(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_service.publish_landing_page。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _publish_landing_page(*args, **kwargs)


def reject_campaign(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_service.reject_campaign。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _reject_campaign(*args, **kwargs)


def save_mkt_settings(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_service.save_mkt_settings。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _save_mkt_settings(*args, **kwargs)


def set_automation_enabled(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_service.set_automation_enabled。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _set_automation_enabled(*args, **kwargs)


def unpublish_landing_page(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_service.unpublish_landing_page。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _unpublish_landing_page(*args, **kwargs)


def update_coupon_batch(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_service.update_coupon_batch。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _update_coupon_batch(*args, **kwargs)


def update_coupon_status(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_service.update_coupon_status。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _update_coupon_status(*args, **kwargs)


def update_landing_page(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_service.update_landing_page。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _update_landing_page(*args, **kwargs)


def upsert_automation(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_service.upsert_automation。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _upsert_automation(*args, **kwargs)


def verify_coupon(*args, **kwargs):
    """薄包装 — 调 mkt.mkt_service.verify_coupon。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _verify_coupon(*args, **kwargs)


def resolve_filter_spec(*args, **kwargs):
    """薄包装 — 调 mkt.segment_nl_intent.resolve_filter_spec。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _resolve_filter_spec(*args, **kwargs)


def stream_nl_segment_query(*args, **kwargs):
    """薄包装 — 调 mkt.segment_nl_intent.stream_nl_segment_query。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _stream_nl_segment_query(*args, **kwargs)


def redeem_guest_coupon(*args, **kwargs):
    """薄包装 — 调 mkt.wallet_service.redeem_guest_coupon。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _redeem_guest_coupon(*args, **kwargs)


def lookup_coupon_by_code(*args, **kwargs):
    """薄包装 — 调 mkt.wallet_service.lookup_coupon_by_code。



    facade 层：业务异常透传；参数校验、事务边界后续补充。

    """

    return _lookup_coupon_by_code(*args, **kwargs)


from mkt.xhs_webhook import (
    binding_public_urls as _binding_public_urls,
)
from mkt.xhs_webhook import (
    extract_signature as _extract_signature,
)
from mkt.xhs_webhook import (
    ingest_xhs_webhook as _ingest_xhs_webhook,
)
from mkt.xhs_webhook import (
    new_binding_token as _new_binding_token,
)
from mkt.xhs_webhook import (
    resolve_binding as _resolve_binding,
)
from mkt.xhs_webhook import (
    verify_webhook_signature as _verify_webhook_signature,
)


def binding_public_urls(*args, **kwargs):
    """薄包装 — 调 mkt.xhs_webhook.binding_public_urls。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _binding_public_urls(*args, **kwargs)


def extract_signature(*args, **kwargs):
    """薄包装 — 调 mkt.xhs_webhook.extract_signature。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _extract_signature(*args, **kwargs)


def ingest_xhs_webhook(*args, **kwargs):
    """薄包装 — 调 mkt.xhs_webhook.ingest_xhs_webhook。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _ingest_xhs_webhook(*args, **kwargs)


def new_binding_token(*args, **kwargs):
    """薄包装 — 调 mkt.xhs_webhook.new_binding_token。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _new_binding_token(*args, **kwargs)


def resolve_binding(*args, **kwargs):
    """薄包装 — 调 mkt.xhs_webhook.resolve_binding。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _resolve_binding(*args, **kwargs)


def verify_webhook_signature(*args, **kwargs):
    """薄包装 — 调 mkt.xhs_webhook.verify_webhook_signature。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _verify_webhook_signature(*args, **kwargs)


# --- orchestrated ---
from sqlalchemy.orm import Session

from mkt.channel_campaign_service import (
    create_channel_campaign as _create_channel_campaign,
)
from mkt.channel_campaign_service import (
    list_channel_campaigns as _list_channel_campaigns,
)


def list_channel_campaigns(db: Session, hotel_id: int, *, limit: int = 40):
    return _list_channel_campaigns(db, hotel_id, limit=limit)


def create_channel_campaign(db: Session, hotel_id: int, payload: dict) -> dict:
    try:
        out = _create_channel_campaign(db, hotel_id, payload)
        db.commit()
        return out
    except Exception:
        db.rollback()
        raise


def redeem_instance(db: Session, *args, **kwargs):
    """核销编排：service flush + facade commit。"""
    try:
        out = _redeem_instance(db, *args, **kwargs)
        db.commit()
        return out
    except Exception:
        db.rollback()
        raise


def create_coupon(db: Session, *args, **kwargs):
    try:
        out = _create_coupon(db, *args, **kwargs)
        db.commit()
        return out
    except Exception:
        db.rollback()
        raise


def grant_coupon(db: Session, *args, **kwargs):
    try:
        out = _grant_coupon(db, *args, **kwargs)
        db.commit()
        return out
    except Exception:
        db.rollback()
        raise
