# SPDX-License-Identifier: Apache-2.0
"""auto-generated facade module for pricing domain.

Auto-generated by gen_facades.py on demand. Do not edit by hand.

职责：
  - 调 service 函数 + 透传 BusinessError
  - 未来扩展：参数校验、事务边界、跨 service 编排
"""

from __future__ import annotations

# 业务异常（透传用）
from domain import (  # noqa: F401
    AuthorizationError,
    BusinessError,
    ConflictError,
    InvalidStateError,
    NotFoundError,
    ValidationError,
)
from infra.commercial_pack import bind as _cbind
from pricing.pricing_assistant import (
    add_competitor as _add_competitor,
)
from pricing.pricing_assistant import (
    add_room_map as _add_room_map,
)
from pricing.pricing_assistant import (
    batch_decide as _batch_decide,
)
from pricing.pricing_assistant import (
    build_calendar as _build_calendar,
)
from pricing.pricing_assistant import (
    build_overview as _build_overview,
)
from pricing.pricing_assistant import (
    build_trend as _build_trend,
)
from pricing.pricing_assistant import (
    create_event as _create_event,
)
from pricing.pricing_assistant import (
    deactivate_competitor as _deactivate_competitor,
)
from pricing.pricing_assistant import (
    deactivate_event as _deactivate_event,
)
from pricing.pricing_assistant import (
    decide_recommendation as _decide_recommendation,
)
from pricing.pricing_assistant import (
    delete_event as _delete_event,
)
from pricing.pricing_assistant import (
    generate_recommendations as _generate_recommendations,
)
from pricing.pricing_assistant import (
    get_config_dict as _get_config_dict,
)
from pricing.pricing_assistant import (
    get_recommendation as _get_recommendation,
)
from pricing.pricing_assistant import (
    import_competitor_rates_csv as _import_competitor_rates_csv,
)
from pricing.pricing_assistant import (
    list_alerts as _list_alerts,
)
from pricing.pricing_assistant import (
    list_competitor_rates as _list_competitor_rates,
)
from pricing.pricing_assistant import (
    list_competitor_sets as _list_competitor_sets,
)
from pricing.pricing_assistant import (
    list_data_sources as _list_data_sources,
)
from pricing.pricing_assistant import (
    list_events as _list_events,
)
from pricing.pricing_assistant import (
    list_recommendations as _list_recommendations,
)
from pricing.pricing_assistant import (
    list_room_maps as _list_room_maps,
)
from pricing.pricing_assistant import (
    run_simulate as _run_simulate,
)
from pricing.pricing_assistant import (
    sync_commission_from_channels as _sync_commission_from_channels,
)
from pricing.pricing_assistant import (
    update_config as _update_config,
)
from pricing.pricing_assistant import (
    update_event as _update_event,
)
from pricing.pricing_assistant import (
    upsert_competitor_rate as _upsert_competitor_rate,
)

_narrate_explain_with_llm = _cbind("commercial.pricing.llm_service", "narrate_explain_with_llm")


def add_competitor(*args, **kwargs):
    """薄包装 — 调 pricing.pricing_assistant.add_competitor。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _add_competitor(*args, **kwargs)


def add_room_map(*args, **kwargs):
    """薄包装 — 调 pricing.pricing_assistant.add_room_map。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _add_room_map(*args, **kwargs)


def batch_decide(*args, **kwargs):
    """薄包装 — 调 pricing.pricing_assistant.batch_decide。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _batch_decide(*args, **kwargs)


def build_calendar(*args, **kwargs):
    """薄包装 — 调 pricing.pricing_assistant.build_calendar。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _build_calendar(*args, **kwargs)


def build_overview(*args, **kwargs):
    """薄包装 — 调 pricing.pricing_assistant.build_overview。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _build_overview(*args, **kwargs)


def build_trend(*args, **kwargs):
    """薄包装 — 调 pricing.pricing_assistant.build_trend。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _build_trend(*args, **kwargs)


def create_event(*args, **kwargs):
    """薄包装 — 调 pricing.pricing_assistant.create_event。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _create_event(*args, **kwargs)


def deactivate_competitor(*args, **kwargs):
    """薄包装 — 调 pricing.pricing_assistant.deactivate_competitor。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _deactivate_competitor(*args, **kwargs)


def deactivate_event(*args, **kwargs):
    """薄包装 — 调 pricing.pricing_assistant.deactivate_event。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _deactivate_event(*args, **kwargs)


def decide_recommendation(*args, **kwargs):
    """薄包装 — 调 pricing.pricing_assistant.decide_recommendation。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _decide_recommendation(*args, **kwargs)


def delete_event(*args, **kwargs):
    """薄包装 — 调 pricing.pricing_assistant.delete_event。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _delete_event(*args, **kwargs)


def generate_recommendations(*args, **kwargs):
    """薄包装 — 调 pricing.pricing_assistant.generate_recommendations。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _generate_recommendations(*args, **kwargs)


def get_config_dict(*args, **kwargs):
    """薄包装 — 调 pricing.pricing_assistant.get_config_dict。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _get_config_dict(*args, **kwargs)


def get_recommendation(*args, **kwargs):
    """薄包装 — 调 pricing.pricing_assistant.get_recommendation。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _get_recommendation(*args, **kwargs)


def import_competitor_rates_csv(*args, **kwargs):
    """薄包装 — 调 pricing.pricing_assistant.import_competitor_rates_csv。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _import_competitor_rates_csv(*args, **kwargs)


def list_alerts(*args, **kwargs):
    """薄包装 — 调 pricing.pricing_assistant.list_alerts。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _list_alerts(*args, **kwargs)


def list_competitor_rates(*args, **kwargs):
    """薄包装 — 调 pricing.pricing_assistant.list_competitor_rates。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _list_competitor_rates(*args, **kwargs)


def list_competitor_sets(*args, **kwargs):
    """薄包装 — 调 pricing.pricing_assistant.list_competitor_sets。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _list_competitor_sets(*args, **kwargs)


def list_data_sources(*args, **kwargs):
    """薄包装 — 调 pricing.pricing_assistant.list_data_sources。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _list_data_sources(*args, **kwargs)


def list_events(*args, **kwargs):
    """薄包装 — 调 pricing.pricing_assistant.list_events。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _list_events(*args, **kwargs)


def list_recommendations(*args, **kwargs):
    """薄包装 — 调 pricing.pricing_assistant.list_recommendations。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _list_recommendations(*args, **kwargs)


def list_room_maps(*args, **kwargs):
    """薄包装 — 调 pricing.pricing_assistant.list_room_maps。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _list_room_maps(*args, **kwargs)


def narrate_explain_with_llm(*args, **kwargs):
    """薄包装 — 调 pricing.pricing_assistant.narrate_explain_with_llm。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _narrate_explain_with_llm(*args, **kwargs)


def run_simulate(*args, **kwargs):
    """薄包装 — 调 pricing.pricing_assistant.run_simulate。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _run_simulate(*args, **kwargs)


def sync_commission_from_channels(*args, **kwargs):
    """薄包装 — 调 pricing.pricing_assistant.sync_commission_from_channels。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _sync_commission_from_channels(*args, **kwargs)


def update_config(*args, **kwargs):
    """薄包装 — 调 pricing.pricing_assistant.update_config。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _update_config(*args, **kwargs)


def update_event(*args, **kwargs):
    """薄包装 — 调 pricing.pricing_assistant.update_event。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _update_event(*args, **kwargs)


def upsert_competitor_rate(*args, **kwargs):
    """薄包装 — 调 pricing.pricing_assistant.upsert_competitor_rate。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _upsert_competitor_rate(*args, **kwargs)


# --- orchestrated ---
from sqlalchemy.orm import Session

from pricing.price_suggestion_service import (
    decide_price_suggestion as _decide_price_suggestion,
)
from pricing.price_suggestion_service import (
    list_price_suggestions as _list_price_suggestions,
)


def list_price_suggestions(db: Session, hotel_id: int):
    return _list_price_suggestions(db, hotel_id)


def decide_price_suggestion(db: Session, pid: int, *, action: str) -> dict:
    try:
        out = _decide_price_suggestion(db, pid, action=action)
        db.commit()
        return out
    except Exception:
        db.rollback()
        raise


def generate_recommendations_tx(*args, **kwargs):
    """生成建议并 commit。"""
    db = args[0]
    try:
        out = _generate_recommendations(*args, **kwargs)
        db.commit()
        return out
    except Exception:
        db.rollback()
        raise
