# SPDX-License-Identifier: Apache-2.0
"""auto-generated facade module for wecom domain.

Auto-generated by gen_facades.py on demand. Do not edit by hand.

职责：
  - 调 service 函数 + 透传 BusinessError
  - 未来扩展：参数校验、事务边界、跨 service 编排
"""

from __future__ import annotations

# 业务异常（透传用）
from domain import (  # noqa: F401
    AuthorizationError,
    BusinessError,
    ConflictError,
    InvalidStateError,
    NotFoundError,
    ValidationError,
)
from wecom.wecom_crypto import (
    parse_event_xml as _parse_event_xml,
)
from wecom.wecom_jssdk import (
    build_jssdk_signatures as _build_jssdk_signatures,
)
from wecom.wecom_service import (
    _resolve_member_landing_page_key as __resolve_member_landing_page_key,
)
from wecom.wecom_service import (
    _resolve_welcome_landing_page_key as __resolve_welcome_landing_page_key,
)
from wecom.wecom_service import (
    dismiss_phone_conflict as _dismiss_phone_conflict,
)
from wecom.wecom_service import (
    draft_wecom_care_message as _draft_wecom_care_message,
)
from wecom.wecom_service import (
    get_bind_ticket_public as _get_bind_ticket_public,
)
from wecom.wecom_service import (
    get_guest_portal as _get_guest_portal,
)
from wecom.wecom_service import (
    list_bind_tickets as _list_bind_tickets,
)
from wecom.wecom_service import (
    list_callback_inbox as _list_callback_inbox,
)
from wecom.wecom_service import (
    list_msg_tasks as _list_msg_tasks,
)
from wecom.wecom_service import (
    list_phone_conflicts as _list_phone_conflicts,
)
from wecom.wecom_service import (
    load_wecom_config as _load_wecom_config,
)
from wecom.wecom_service import (
    log_sidebar_care_sent as _log_sidebar_care_sent,
)
from wecom.wecom_service import (
    query_groupmsg_result as _query_groupmsg_result,
)
from wecom.wecom_service import (
    resolve_phone_conflict as _resolve_phone_conflict,
)
from wecom.wecom_service import (
    send_care_direct_message as _send_care_direct_message,
)
from wecom.wecom_service import (
    sidebar_guest_by_external_userid as _sidebar_guest_by_external_userid,
)
from wecom.wecom_service import (
    simulate_friend_scan as _simulate_friend_scan,
)
from wecom.wecom_service import (
    test_wecom_connection as _test_wecom_connection,
)


def parse_event_xml(*args, **kwargs):
    """薄包装 — 调 wecom.wecom_crypto.parse_event_xml。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _parse_event_xml(*args, **kwargs)


def build_jssdk_signatures(*args, **kwargs):
    """薄包装 — 调 wecom.wecom_jssdk.build_jssdk_signatures。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _build_jssdk_signatures(*args, **kwargs)


def _resolve_member_landing_page_key(*args, **kwargs):
    """薄包装 — 调 wecom.wecom_service._resolve_member_landing_page_key。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return __resolve_member_landing_page_key(*args, **kwargs)


def _resolve_welcome_landing_page_key(*args, **kwargs):
    """薄包装 — 调 wecom.wecom_service._resolve_welcome_landing_page_key。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return __resolve_welcome_landing_page_key(*args, **kwargs)


def dismiss_phone_conflict(*args, **kwargs):
    """薄包装 — 调 wecom.wecom_service.dismiss_phone_conflict。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _dismiss_phone_conflict(*args, **kwargs)


def draft_wecom_care_message(*args, **kwargs):
    """薄包装 — 调 wecom.wecom_service.draft_wecom_care_message。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _draft_wecom_care_message(*args, **kwargs)


def get_bind_ticket_public(*args, **kwargs):
    """薄包装 — 调 wecom.wecom_service.get_bind_ticket_public。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _get_bind_ticket_public(*args, **kwargs)


def get_guest_portal(*args, **kwargs):
    """薄包装 — 调 wecom.wecom_service.get_guest_portal。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _get_guest_portal(*args, **kwargs)


def list_bind_tickets(*args, **kwargs):
    """薄包装 — 调 wecom.wecom_service.list_bind_tickets。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _list_bind_tickets(*args, **kwargs)


def list_callback_inbox(*args, **kwargs):
    """薄包装 — 调 wecom.wecom_service.list_callback_inbox。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _list_callback_inbox(*args, **kwargs)


def list_msg_tasks(*args, **kwargs):
    """薄包装 — 调 wecom.wecom_service.list_msg_tasks。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _list_msg_tasks(*args, **kwargs)


def list_phone_conflicts(*args, **kwargs):
    """薄包装 — 调 wecom.wecom_service.list_phone_conflicts。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _list_phone_conflicts(*args, **kwargs)


def load_wecom_config(*args, **kwargs):
    """薄包装 — 调 wecom.wecom_service.load_wecom_config。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _load_wecom_config(*args, **kwargs)


def log_sidebar_care_sent(*args, **kwargs):
    """薄包装 — 调 wecom.wecom_service.log_sidebar_care_sent。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _log_sidebar_care_sent(*args, **kwargs)


def query_groupmsg_result(*args, **kwargs):
    """薄包装 — 调 wecom.wecom_service.query_groupmsg_result。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _query_groupmsg_result(*args, **kwargs)


def resolve_phone_conflict(*args, **kwargs):
    """薄包装 — 调 wecom.wecom_service.resolve_phone_conflict。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _resolve_phone_conflict(*args, **kwargs)


def send_care_direct_message(*args, **kwargs):
    """薄包装 — 调 wecom.wecom_service.send_care_direct_message。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _send_care_direct_message(*args, **kwargs)


def send_single_message(*args, **kwargs):
    """经 messaging 通道发送一对一文本（默认 wecom adapter）。

    兼容原签名：send_single_message(db, hotel_id, guest_id, content)
    """
    from messaging import send_text

    if len(args) >= 4:
        db, hotel_id, guest_id, content = args[0], args[1], args[2], args[3]
        return send_text(hotel_id=hotel_id, content=content, guest_id=guest_id, db=db)
    db = kwargs.pop("db")
    hotel_id = kwargs.pop("hotel_id")
    guest_id = kwargs.pop("guest_id")
    content = kwargs.pop("content")
    return send_text(hotel_id=hotel_id, content=content, guest_id=guest_id, db=db, **kwargs)


def sidebar_guest_by_external_userid(*args, **kwargs):
    """薄包装 — 调 wecom.wecom_service.sidebar_guest_by_external_userid。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _sidebar_guest_by_external_userid(*args, **kwargs)


def simulate_friend_scan(*args, **kwargs):
    """薄包装 — 调 wecom.wecom_service.simulate_friend_scan。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _simulate_friend_scan(*args, **kwargs)


def sync_external_contacts(*args, **kwargs):
    """经 messaging 通道同步外部联系人（默认 wecom adapter）。

    兼容原签名：sync_external_contacts(db, hotel_id)
    """
    from messaging import sync_external_contacts as _sync

    if len(args) >= 2:
        db, hotel_id = args[0], args[1]
        return _sync(hotel_id, db=db)
    db = kwargs.pop("db")
    hotel_id = kwargs.pop("hotel_id")
    return _sync(hotel_id, db=db, **kwargs)


def test_wecom_connection(*args, **kwargs):
    """薄包装 — 调 wecom.wecom_service.test_wecom_connection。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _test_wecom_connection(*args, **kwargs)


from wecom.wecom_portal_auth import (
    exchange_oauth_identity as _exchange_oauth_identity,
)
from wecom.wecom_portal_auth import (
    issue_portal_session as _issue_portal_session,
)


def exchange_oauth_identity(*args, **kwargs):
    """薄包装 — 调 wecom.wecom_portal_auth.exchange_oauth_identity。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _exchange_oauth_identity(*args, **kwargs)


def issue_portal_session(*args, **kwargs):
    """薄包装 — 调 wecom.wecom_portal_auth.issue_portal_session。

    facade 层：业务异常透传；参数校验、事务边界后续补充。
    """
    return _issue_portal_session(*args, **kwargs)


# --- read queries ---


def get_bind_ticket_by_token(*args, **kwargs):
    """按 token 查 WecomBindTicket（OAuth / portal / bind 落地页共用）。"""
    from wecom.wecom_service.ticket_query import get_bind_ticket_by_token as _get

    return _get(*args, **kwargs)


# --- orchestrated ---


def save_wecom_config(db, payload: dict) -> dict:
    """保存企微配置编排入口（service 内仍 commit；facade 统一对外）。"""
    from wecom.wecom_service import mask_wecom_config
    from wecom.wecom_service import save_wecom_config as _save

    saved = _save(db, payload)
    return mask_wecom_config(saved)


def load_wecom_config_masked(db) -> dict:
    from wecom.wecom_service import load_wecom_config, mask_wecom_config

    return mask_wecom_config(load_wecom_config(db))


def _portal_url(*args, **kwargs):
    from wecom.wecom_service import _portal_url as _fn

    return _fn(*args, **kwargs)


def _resolve_returning_landing_page_key(*args, **kwargs):
    from wecom.wecom_service import _resolve_returning_landing_page_key as _fn

    return _fn(*args, **kwargs)
