# SPDX-License-Identifier: Apache-2.0
"""团体订单：扩展字段 + 房量块 + 分房清单。"""

from __future__ import annotations

from sqlalchemy import inspect, text
from sqlalchemy.engine import Engine

GROUP_LINE_SQL = """
CREATE TABLE IF NOT EXISTS pms_group_room_lines (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hotel_id INTEGER NOT NULL REFERENCES hotels(id) ON DELETE CASCADE,
    order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    line_no SMALLINT DEFAULT 1,
    room_type_id INTEGER REFERENCES room_types(id) ON DELETE SET NULL,
    guest_name VARCHAR(80),
    guest_phone VARCHAR(30),
    id_last4 VARCHAR(8),
    room_id INTEGER REFERENCES rooms(id) ON DELETE SET NULL,
    checkin_id INTEGER REFERENCES pms_checkins(id) ON DELETE SET NULL,
    stay_check_in DATE,
    stay_check_out DATE,
    status VARCHAR(20) DEFAULT 'held',
    note VARCHAR(200),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
"""

GROUP_BLOCK_SQL = """
CREATE TABLE IF NOT EXISTS pms_group_room_blocks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hotel_id INTEGER NOT NULL REFERENCES hotels(id) ON DELETE CASCADE,
    order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    room_type_id INTEGER REFERENCES room_types(id) ON DELETE SET NULL,
    qty SMALLINT DEFAULT 1,
    unit_price NUMERIC(10,2) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
"""

ORDER_GROUP_COLS = [
    ("group_name", "VARCHAR(120)"),
    ("group_type", "VARCHAR(40)"),
    ("settle_mode", "VARCHAR(40) DEFAULT 'unified'"),
    ("settle_party", "VARCHAR(120)"),
    ("sales_name", "VARCHAR(80)"),
    ("other_amount", "NUMERIC(12,2) DEFAULT 0"),
]

LINE_EXTRA_COLS = [
    ("id_last4", "VARCHAR(8)"),
    ("stay_check_in", "DATE"),
    ("stay_check_out", "DATE"),
]


def ensure_group_orders_schema(engine: Engine) -> None:
    insp = inspect(engine)
    with engine.begin() as conn:
        insp_conn = inspect(conn)
        if insp_conn.has_table("orders"):
            cols = {c["name"] for c in insp_conn.get_columns("orders")}
            for name, ddl in ORDER_GROUP_COLS:
                if name not in cols:
                    conn.execute(text(f"ALTER TABLE orders ADD COLUMN {name} {ddl}"))
        conn.execute(text(GROUP_LINE_SQL))
        conn.execute(text(GROUP_BLOCK_SQL))
        if insp_conn.has_table("pms_group_room_lines"):
            line_cols = {c["name"] for c in insp_conn.get_columns("pms_group_room_lines")}
            for name, ddl in LINE_EXTRA_COLS:
                if name not in line_cols:
                    conn.execute(text(f"ALTER TABLE pms_group_room_lines ADD COLUMN {name} {ddl}"))
