# SPDX-License-Identifier: Apache-2.0
"""OneID 归并审计：schema 保活 + 历史数据回填。

i18n 中文映射已抽到 `guests.i18n_cn`；身份仿真 / 事件生成 helper 已抽到
`guests.identity_sim`；本文件保留 schema 保活与回填入口函数。
"""

from __future__ import annotations

from datetime import datetime, timedelta
from typing import Iterable

from sqlalchemy import inspect, text
from sqlalchemy.orm import Session

from guests.i18n_cn import ACTION_CN, MERGE_METHOD_CN, SRC_CN, action_cn, merge_method_cn, source_cn
from guests.identity_sim import (
    _rng,
    build_event_note,
    enrich_identity_dict,
    guest_timeline_anchor,
    infer_merge_method,
    infer_operator,
    realistic_confidence,
    realistic_external_id,
)
from models import Guest, GuestIdentity, OneIdMergeEvent, Order


def ensure_oneid_audit_schema(engine) -> None:
    insp = inspect(engine)
    if not insp.has_table("oneid_merge_events"):
        with engine.begin() as conn:
            conn.execute(
                text("""
                CREATE TABLE oneid_merge_events (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    guest_id INTEGER NOT NULL REFERENCES guests(id) ON DELETE CASCADE,
                    action VARCHAR(30) NOT NULL,
                    source VARCHAR(30),
                    external_id VARCHAR(120),
                    confidence NUMERIC(3, 2),
                    merge_method VARCHAR(30),
                    operator VARCHAR(60),
                    note TEXT,
                    occurred_at TIMESTAMP NOT NULL
                )
            """)
            )
            conn.execute(
                text(
                    "CREATE INDEX IF NOT EXISTS ix_oneid_merge_events_guest ON oneid_merge_events(guest_id, occurred_at)"
                )
            )
    cols = {c["name"] for c in insp.get_columns("guest_identities")} if insp.has_table("guest_identities") else set()
    alters = []
    if "is_primary" not in cols:
        alters.append("ALTER TABLE guest_identities ADD COLUMN is_primary BOOLEAN DEFAULT FALSE")
    if "merge_method" not in cols:
        alters.append("ALTER TABLE guest_identities ADD COLUMN merge_method VARCHAR(30)")
    if "matched_by" not in cols:
        alters.append("ALTER TABLE guest_identities ADD COLUMN matched_by VARCHAR(60)")
    if alters:
        with engine.begin() as conn:
            for sql in alters:
                conn.execute(text(sql))


def create_realistic_identities(db: Session, guest: Guest, sources: Iterable[str]) -> list[GuestIdentity]:
    src_list = list(dict.fromkeys(sources))
    if not src_list:
        src_list = ["direct"]
    anchor = guest_timeline_anchor(db, guest)
    rng = _rng(guest.id, "ident")
    rows: list[GuestIdentity] = []
    for idx, src in enumerate(src_list):
        is_primary = idx == 0
        conf = realistic_confidence(rng, is_primary)
        method = infer_merge_method(conf, is_primary)
        linked = anchor + timedelta(days=idx * rng.randint(7, 35), hours=rng.randint(1, 6), minutes=rng.randint(0, 59))
        row = GuestIdentity(
            guest_id=guest.id,
            source=src,
            external_id=realistic_external_id(src, guest, idx),
            confidence=conf,
            linked_at=linked,
            is_primary=is_primary,
            merge_method=method,
            matched_by=infer_operator(method),
        )
        db.add(row)
        rows.append(row)
    db.flush()
    return rows


def rebuild_events_for_guest(db: Session, guest: Guest, idents: list[GuestIdentity]) -> int:
    db.query(OneIdMergeEvent).filter_by(guest_id=guest.id).delete()
    if not idents:
        idents = list(
            db.query(GuestIdentity).filter_by(guest_id=guest.id).order_by(GuestIdentity.linked_at.asc()).all()
        )
    if not idents:
        return 0
    idents = sorted(idents, key=lambda x: (x.linked_at or datetime.min, x.id or 0))
    anchor = guest_timeline_anchor(db, guest)
    born_at = guest.created_at or (anchor - timedelta(days=1))
    if born_at > (idents[0].linked_at or born_at):
        born_at = (idents[0].linked_at or anchor) - timedelta(hours=2)
    events: list[OneIdMergeEvent] = []
    events.append(
        OneIdMergeEvent(
            guest_id=guest.id,
            action="oneid_born",
            source="system",
            external_id=guest.one_id,
            confidence=1.0,
            merge_method="primary_bind",
            operator="系统自动",
            note=build_event_note("oneid_born", guest, "system", guest.one_id or "", 1.0, "primary_bind"),
            occurred_at=born_at,
        )
    )
    for idx, ident in enumerate(idents):
        src = (ident.source or "").lower()
        method = ident.merge_method or infer_merge_method(float(ident.confidence or 0), idx == 0)
        conf = float(ident.confidence or 0)
        action = "primary_bind" if idx == 0 else "channel_merge"
        at = ident.linked_at or anchor + timedelta(days=idx * 14)
        events.append(
            OneIdMergeEvent(
                guest_id=guest.id,
                action=action,
                source=ident.source,
                external_id=ident.external_id,
                confidence=conf,
                merge_method=method,
                operator=ident.matched_by or infer_operator(method),
                note=build_event_note(action, guest, src, ident.external_id or "—", conf, method),
                occurred_at=at,
            )
        )
        if method == "manual_review" and conf < 0.85:
            events.append(
                OneIdMergeEvent(
                    guest_id=guest.id,
                    action="merge_confirm",
                    source=ident.source,
                    external_id=ident.external_id,
                    confidence=conf,
                    merge_method="manual_review",
                    operator="前台运营",
                    note=f"人工确认归并有效，外部账号 {ident.external_id} 与主档手机号尾号一致。",
                    occurred_at=at + timedelta(hours=2, minutes=15),
                )
            )
    for ev in events:
        db.add(ev)
    db.flush()
    return len(events)


def backfill_guest_identities(db: Session, guest: Guest) -> list[GuestIdentity]:
    idents = db.query(GuestIdentity).filter_by(guest_id=guest.id).order_by(GuestIdentity.id.asc()).all()
    if not idents:
        rng = _rng(guest.id, "src")
        n = rng.randint(1, 3)
        sources = rng.sample(["ota", "xiaohongshu", "wechat", "direct", "douyin"], n)
        return create_realistic_identities(db, guest, sources)

    anchor = guest_timeline_anchor(db, guest)
    rng = _rng(guest.id, "backfill")
    for idx, ident in enumerate(idents):
        src = (ident.source or "direct").lower()
        if not ident.external_id or "-" in ident.external_id and ident.external_id.split("-")[-1].isdigit():
            ident.external_id = realistic_external_id(src, guest, idx)
        is_primary = idx == 0
        if ident.is_primary is None:
            ident.is_primary = is_primary
        conf = float(ident.confidence or 0)
        if conf <= 0 or (conf == 1.0 and not is_primary):
            conf = realistic_confidence(rng, is_primary)
            ident.confidence = conf
        method = ident.merge_method or infer_merge_method(conf, is_primary)
        ident.merge_method = method
        ident.matched_by = ident.matched_by or infer_operator(method)
        ident.linked_at = anchor + timedelta(
            days=idx * rng.randint(5, 28),
            hours=rng.randint(0, 10),
            minutes=rng.randint(0, 59),
        )
    if guest.created_at is None or guest.created_at > (idents[0].linked_at or anchor):
        guest.created_at = anchor - timedelta(days=1, hours=3)
    db.flush()
    return idents


def ensure_oneid_audit_realism(db: Session, force_rebuild_events: bool = False) -> dict:
    guests = db.query(Guest).order_by(Guest.id.asc()).all()
    events_added = 0
    identities_updated = 0
    for g in guests:
        idents = backfill_guest_identities(db, g)
        identities_updated += len(idents)
        existing = db.query(OneIdMergeEvent).filter_by(guest_id=g.id).count()
        if existing == 0 or force_rebuild_events:
            events_added += rebuild_events_for_guest(db, g, idents)
    db.commit()
    return {
        "guests": len(guests),
        "identities_touched": identities_updated,
        "events_written": events_added,
    }
