# SPDX-License-Identifier: Apache-2.0
"""押金表结构 + 种子数据。"""

from __future__ import annotations

from datetime import datetime, timedelta

from sqlalchemy import text
from sqlalchemy.orm import Session

from models import Deposit, DepositLedgerEntry, Guest, Order, PmsCheckin
from seed.locale_pack import seed_text


def ensure_deposits_schema(engine) -> None:
    with engine.begin() as conn:
        conn.execute(
            text(
                """
                CREATE TABLE IF NOT EXISTS deposits (
                    deposit_id VARCHAR(32) PRIMARY KEY,
                    hotel_id INTEGER NOT NULL REFERENCES hotels(id) ON DELETE CASCADE,
                    order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
                    customer_id VARCHAR(64) NOT NULL,
                    guest_id INTEGER REFERENCES guests(id) ON DELETE SET NULL,
                    room_no VARCHAR(8) NOT NULL,
                    form VARCHAR(24) NOT NULL,
                    original_amount INTEGER NOT NULL,
                    captured_amount INTEGER NOT NULL DEFAULT 0,
                    remaining_refund INTEGER NOT NULL DEFAULT 0,
                    status VARCHAR(32) NOT NULL DEFAULT 'CREATED',
                    auth_code VARCHAR(64),
                    auth_expire_at TIMESTAMP,
                    ar_account_id VARCHAR(32),
                    receipt_no VARCHAR(32),
                    operator_id VARCHAR(32) NOT NULL DEFAULT 'system',
                    idempotency_key VARCHAR(64) UNIQUE,
                    guest_name VARCHAR(80),
                    order_no VARCHAR(40),
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    released_at TIMESTAMP,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
                """
            )
        )
        conn.execute(
            text(
                """
                CREATE TABLE IF NOT EXISTS deposit_ledger_entries (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    deposit_id VARCHAR(32) NOT NULL REFERENCES deposits(deposit_id) ON DELETE CASCADE,
                    event VARCHAR(32) NOT NULL,
                    from_status VARCHAR(32),
                    to_status VARCHAR(32),
                    amount_delta INTEGER DEFAULT 0,
                    operator_id VARCHAR(32),
                    channel_ref VARCHAR(64),
                    memo VARCHAR(255),
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
                """
            )
        )
        conn.execute(text("CREATE INDEX IF NOT EXISTS ix_deposits_hotel_status ON deposits(hotel_id, status)"))
        conn.execute(text("CREATE INDEX IF NOT EXISTS ix_deposits_order ON deposits(order_id)"))
        conn.execute(text("CREATE INDEX IF NOT EXISTS ix_deposits_customer ON deposits(customer_id)"))


def _room_for(db: Session, order: Order) -> str:
    ck = db.query(PmsCheckin).filter_by(order_id=order.id).order_by(PmsCheckin.id.desc()).first()
    if ck and ck.room_no:
        return str(ck.room_no)[:8]
    return f"{1000 + (order.id % 900):04d}"[:8]


def seed_deposits_demo(db: Session, hotel_id: int = 1) -> dict:
    """空库时写入与原型对齐的押金（含异常）。"""
    n = db.query(Deposit).filter_by(hotel_id=hotel_id).count()
    if n > 0:
        return {"skipped": True, "existing": n, "added": 0}

    orders = db.query(Order).filter(Order.hotel_id == hotel_id).order_by(Order.id.desc()).limit(12).all()
    if len(orders) < 4:
        return {"skipped": True, "reason": "orders_insufficient", "added": 0}

    now = datetime.now()
    day = now.strftime("%Y%m%d")
    samples = [
        # 在押 · 微信
        dict(
            idx=0,
            form="WECHAT_DEPOSIT",
            status="FROZEN",
            amount=100000,
            auth=True,
            expire_days=30,
            guest_fallback=seed_text("张女士", "Ms. Zhang"),
        ),
        # 预授权过期
        dict(
            idx=1,
            form="PREAUTH_CARD",
            status="EXPIRED",
            amount=150000,
            auth=True,
            expire_days=-3,
            guest_fallback=seed_text("王女士", "Ms. Wang"),
            room_override="1512",
        ),
        # 在押不足
        dict(
            idx=2,
            form="WECHAT_DEPOSIT",
            status="PARTIAL_CAPTURE",
            amount=50000,
            captured=30000,
            auth=True,
            expire_days=20,
            guest_fallback=seed_text("刘先生", "Mr. Liu"),
            room_override="0908",
        ),
        # 争议
        dict(
            idx=3,
            form="WECHAT_DEPOSIT",
            status="DISPUTED",
            amount=80000,
            auth=True,
            expire_days=15,
            guest_fallback=seed_text("孙先生", "Mr. Sun"),
            room_override="1105",
            updated_hours_ago=18,
        ),
        # 现金无收据
        dict(
            idx=4,
            form="CASH",
            status="FROZEN",
            amount=50000,
            receipt=None,
            guest_fallback=seed_text("蒋阿姨", "Auntie Jiang"),
            room_override="0603",
        ),
        # 正常在押 · 挂账免押类展示用小额 AR
        dict(
            idx=5,
            form="AR",
            status="FROZEN",
            amount=0,
            waived_display=True,
            guest_fallback=seed_text("协议客", "Corp guest"),
        ),
        # 今日已退
        dict(
            idx=6,
            form="WECHAT_DEPOSIT",
            status="RELEASED",
            amount=65400,
            auth=True,
            released_today=True,
            guest_fallback=seed_text("已退客人", "Refunded guest"),
        ),
    ]

    added = 0
    for i, s in enumerate(samples):
        if s["idx"] >= len(orders):
            break
        o = orders[s["idx"]]
        g = db.get(Guest, o.guest_id) if o.guest_id else None
        room = s.get("room_override") or _room_for(db, o)
        amount = int(s["amount"])
        captured = int(s.get("captured") or 0)
        remaining = max(0, amount - captured)
        if s.get("status") in ("RELEASED", "RELEASED_AFTER_CAPTURE", "CAPTURED"):
            remaining = 0
        dep_id = f"DPS-{day}-{i + 1:04d}"
        auth_code = None
        auth_expire = None
        if s.get("auth"):
            auth_code = f"AUTH-DEMO-{i + 1:03d}"
            auth_expire = now + timedelta(days=int(s.get("expire_days") or 30))
        receipt = s.get("receipt", "RCPT-OK") if s["form"] == "CASH" else None
        if s["form"] == "CASH" and "receipt" in s and s["receipt"] is None:
            receipt = None

        d = Deposit(
            deposit_id=dep_id,
            hotel_id=hotel_id,
            order_id=o.id,
            customer_id=(g.one_id if g else f"C-SEED-{o.id}"),
            guest_id=o.guest_id,
            room_no=room,
            form=s["form"],
            original_amount=amount,
            captured_amount=captured,
            remaining_refund=remaining,
            status=s["status"],
            auth_code=auth_code,
            auth_expire_at=auth_expire,
            receipt_no=receipt,
            operator_id="seed",
            idempotency_key=f"seed-{hotel_id}-{dep_id}",
            guest_name=(g.name if g else s.get("guest_fallback")),
            order_no=o.order_no,
            released_at=now if s.get("released_today") else None,
            updated_at=now - timedelta(hours=int(s.get("updated_hours_ago") or 0)),
            created_at=now - timedelta(days=2),
        )
        db.add(d)
        db.flush()
        db.add(
            DepositLedgerEntry(
                deposit_id=dep_id,
                event="COLLECT",
                from_status="CREATED",
                to_status="FROZEN",
                amount_delta=amount,
                operator_id="seed",
                memo=seed_text("收押", "Collect"),
            )
        )
        if captured:
            db.add(
                DepositLedgerEntry(
                    deposit_id=dep_id,
                    event="CAPTURE",
                    from_status="FROZEN",
                    to_status="PARTIAL_CAPTURE",
                    amount_delta=-captured,
                    operator_id="seed",
                    memo=seed_text("扣减", "Capture"),
                )
            )
        if s["status"] == "EXPIRED":
            db.add(
                DepositLedgerEntry(
                    deposit_id=dep_id,
                    event="EXPIRE",
                    from_status="FROZEN",
                    to_status="EXPIRED",
                    amount_delta=0,
                    operator_id="system",
                    memo=seed_text("预授权过期", "Pre-auth expired"),
                )
            )
        if s["status"] == "DISPUTED":
            db.add(
                DepositLedgerEntry(
                    deposit_id=dep_id,
                    event="DISPUTE",
                    from_status="FROZEN",
                    to_status="DISPUTED",
                    amount_delta=0,
                    operator_id="seed",
                    memo=seed_text("金额不符", "Amount mismatch"),
                )
            )
        if s.get("released_today"):
            db.add(
                DepositLedgerEntry(
                    deposit_id=dep_id,
                    event="RELEASE",
                    from_status="FROZEN",
                    to_status="RELEASED",
                    amount_delta=-amount,
                    operator_id="seed",
                    memo=seed_text("今日退还", "Refunded today"),
                )
            )
        added += 1

    db.commit()
    return {"skipped": False, "added": added}
