# SPDX-License-Identifier: Apache-2.0
"""客户会员扩展：CRM 任务表、标签种子、分群规则扩展。

CRM 扩展分群 / 标签默认与 `match_rule_extended` 已抽到 `guests.crm_defaults`；
本文件保留 schema 保活与种子入口。
"""

from __future__ import annotations

from sqlalchemy import inspect, text
from sqlalchemy.orm import Session

from bootstrap.ensure_member_crm import DEFAULT_SEGMENTS, match_rule
from guests.crm_defaults import EXTRA_SEGMENTS, EXTRA_TAGS, match_rule_extended
from models import Hotel, Segment, TagDefinition


def ensure_crm_tasks_schema(engine) -> None:
    insp = inspect(engine)
    if insp.has_table("crm_tasks"):
        return
    with engine.begin() as conn:
        conn.execute(
            text("""
            CREATE TABLE crm_tasks (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                hotel_id INTEGER NOT NULL REFERENCES hotels(id) ON DELETE CASCADE,
                guest_id INTEGER REFERENCES guests(id) ON DELETE SET NULL,
                segment_id INTEGER REFERENCES segments(id) ON DELETE SET NULL,
                task_type VARCHAR(30) DEFAULT 'recall',
                status VARCHAR(20) DEFAULT 'open',
                title VARCHAR(200),
                payload_json TEXT,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                done_at TIMESTAMP
            )
        """)
        )


def ensure_extended_tags(db: Session) -> None:
    existing = {t.code: t for t in db.query(TagDefinition).all()}
    for code, name, cat, rule in EXTRA_TAGS:
        if code not in existing:
            db.add(TagDefinition(code=code, name=name, category=cat, rule_expr=rule, is_active=True))
    db.flush()


def ensure_extra_segments(db: Session, hotel_id: int) -> None:
    from bootstrap.ensure_member_crm import _deleted_segment_names

    existing = {s.name: s for s in db.query(Segment).filter_by(hotel_id=hotel_id).all()}
    deleted = _deleted_segment_names(db, hotel_id)
    for name, rule, _tone in EXTRA_SEGMENTS:
        if name in deleted:
            continue
        if name not in existing:
            db.add(Segment(hotel_id=hotel_id, name=name, filter_rule=rule))
    db.flush()


def ensure_crm_extended(db: Session, hotel_id: int | None = None) -> None:
    ensure_extended_tags(db)
    hotels = db.query(Hotel).all()
    targets = [h for h in hotels if hotel_id is None or h.id == hotel_id]
    for h in targets:
        ensure_extra_segments(db, h.id)
    db.commit()
