# SPDX-License-Identifier: Apache-2.0
"""退改与反结账 · 表结构 + 工单。

退款用例数据常量已抽到 `finance.refund_defaults`；本文件保留 schema 保活与种子函数。
"""

from __future__ import annotations

from datetime import date, datetime, timedelta
from decimal import Decimal

from sqlalchemy import text
from sqlalchemy.orm import Session

from finance.refund_defaults import REFUND_CASE_ORDERS, REFUND_CASE_PHONE, REFUND_CASE_ROOM
from models import (
    Guest,
    Order,
    Payment,
    PmsCheckin,
    PmsFolio,
    PmsFolioEntry,
    RefundAdjustAudit,
    RefundAdjustConfig,
    RefundAdjustTicket,
    Room,
)
from seed.locale_pack import seed_text


def ensure_refund_adjust_schema(engine) -> None:
    with engine.begin() as conn:
        conn.execute(
            text(
                """
                CREATE TABLE IF NOT EXISTS refund_adjust_configs (
                    hotel_id INTEGER PRIMARY KEY REFERENCES hotels(id) ON DELETE CASCADE,
                    refund_threshold_yuan INTEGER NOT NULL DEFAULT 2000,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
                """
            )
        )
        conn.execute(
            text(
                """
                CREATE TABLE IF NOT EXISTS refund_adjust_tickets (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ticket_no VARCHAR(40) NOT NULL UNIQUE,
                    hotel_id INTEGER NOT NULL REFERENCES hotels(id) ON DELETE CASCADE,
                    op_type VARCHAR(20) NOT NULL,
                    status VARCHAR(32) NOT NULL DEFAULT 'pending_approval',
                    title VARCHAR(120) NOT NULL,
                    detail VARCHAR(255),
                    order_id INTEGER REFERENCES orders(id) ON DELETE SET NULL,
                    order_no VARCHAR(40),
                    guest_name_masked VARCHAR(40),
                    amount_cents INTEGER DEFAULT 0,
                    reason VARCHAR(200),
                    refund_method VARCHAR(40),
                    applicant_id VARCHAR(40),
                    auth_mgr_done INTEGER DEFAULT 0,
                    auth_fin_done INTEGER DEFAULT 0,
                    auth_mgr_by VARCHAR(40),
                    auth_fin_by VARCHAR(40),
                    payload_json TEXT,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
                """
            )
        )
        conn.execute(
            text(
                """
                CREATE TABLE IF NOT EXISTS refund_adjust_audits (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    hotel_id INTEGER NOT NULL REFERENCES hotels(id) ON DELETE CASCADE,
                    ticket_id INTEGER REFERENCES refund_adjust_tickets(id) ON DELETE CASCADE,
                    event VARCHAR(40) NOT NULL,
                    actor_id VARCHAR(40),
                    memo VARCHAR(255),
                    before_json TEXT,
                    after_json TEXT,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
                """
            )
        )
        conn.execute(
            text("CREATE INDEX IF NOT EXISTS ix_ra_tickets_hotel_status ON refund_adjust_tickets(hotel_id, status)")
        )


def seed_refund_adjust_demo(db: Session, hotel_id: int = 1) -> dict:
    cfg = db.get(RefundAdjustConfig, hotel_id)
    if not cfg:
        db.add(RefundAdjustConfig(hotel_id=hotel_id, refund_threshold_yuan=2000))
        db.flush()

    existing = db.query(RefundAdjustTicket).filter(RefundAdjustTicket.hotel_id == hotel_id).count()
    if existing:
        return {"skipped": True, "existing": existing}

    samples = [
        dict(
            ticket_no="RA-REF-8821",
            op_type="refund",
            status="pending_approval",
            title=seed_text("部分退款 · No.8821", "Partial refund · No.8821"),
            detail=seed_text("取消 1 晚，退 ¥428", "Cancel 1 night, refund ¥428"),
            order_no="No.8821",
            guest_name_masked=seed_text("王**", "W**"),
            amount_cents=42800,
            reason=seed_text("客人要求取消第 2 晚", "Guest asked to cancel night 2"),
            refund_method="original_wechat",
        ),
        dict(
            ticket_no="RA-REV-1108",
            op_type="reverse",
            status="pending_dual_auth",
            title=seed_text("反结账 · 房 1108", "Folio reverse · Room 1108"),
            detail=seed_text("房费算错，重开账单", "Room charge error — reopen folio"),
            order_no="PY-0829-1108",
            guest_name_masked=seed_text("李**", "L**"),
            amount_cents=85600,
            reason=seed_text("房费算错", "Room charge error"),
            auth_mgr_done=0,
            auth_fin_done=0,
        ),
        dict(
            ticket_no="RA-ADJ-AR76",
            op_type="adjust",
            status="approved",
            title=seed_text("冲正 · 协议挂账早餐", "Adjustment · corp breakfast"),
            detail=seed_text("误收早餐 ¥76", "Breakfast charged in error ¥76"),
            order_no="AR-0829",
            guest_name_masked=seed_text("企**", "C**"),
            amount_cents=7600,
            reason=seed_text("误收早餐费", "Breakfast charged in error"),
        ),
    ]
    now = datetime.now()
    added = 0
    for i, s in enumerate(samples):
        t = RefundAdjustTicket(
            hotel_id=hotel_id,
            applicant_id="demo",
            created_at=now,
            updated_at=now,
            **s,
        )
        db.add(t)
        db.flush()
        db.add(
            RefundAdjustAudit(
                hotel_id=hotel_id,
                ticket_id=t.id,
                event="SEED",
                actor_id="system",
                memo=seed_text("系统初始化工单", "System seed ticket"),
            )
        )
        added += 1
    db.commit()
    return {"skipped": False, "added": added}


def seed_refund_cases_demo(db: Session, hotel_id: int = 1, *, force: bool = False) -> dict:
    """
    退款用例专用数据：手机号优先 / 原路锁定 / 全额退过滤 / 取消过滤 / 工单点入。
    可重复执行：同 order_no 已存在则跳过（force=True 时重建）。
    """
    from infra.id_doc_crypto import pack_phone_fields

    existing = db.query(Order).filter(Order.hotel_id == hotel_id, Order.order_no == REFUND_CASE_ORDERS["wx"]).first()
    if existing and not force:
        # 确保工单挂上 order_id
        _link_refund_case_ticket(db, hotel_id, existing.id)
        db.commit()
        return {
            "skipped": True,
            "order_id": existing.id,
            "phone": REFUND_CASE_PHONE,
            "room": REFUND_CASE_ROOM,
            "orders": list(REFUND_CASE_ORDERS.values()),
        }

    if existing and force:
        for no in REFUND_CASE_ORDERS.values():
            o = db.query(Order).filter_by(hotel_id=hotel_id, order_no=no).first()
            if not o:
                continue
            folios = db.query(PmsFolio).filter_by(order_id=o.id).all()
            for f in folios:
                db.query(PmsFolioEntry).filter_by(folio_id=f.id).delete(synchronize_session=False)
                db.delete(f)
            db.query(Payment).filter_by(order_id=o.id).delete(synchronize_session=False)
            db.query(PmsCheckin).filter_by(order_id=o.id).delete(synchronize_session=False)
            db.delete(o)
        db.flush()

    packed = pack_phone_fields(REFUND_CASE_PHONE, hotel_id)
    guest = db.query(Guest).filter(Guest.phone_hash == packed["phone_hash"]).first()
    if not guest:
        one_id = f"C-RFUND-{hotel_id}-{REFUND_CASE_PHONE[-4:]}"
        guest = Guest(
            one_id=one_id,
            name="王退测",
            phone=packed["phone"],
            phone_cipher=packed["phone_cipher"],
            phone_mask=packed["phone_mask"],
            phone_hash=packed["phone_hash"],
            city="退款用例",
        )
        db.add(guest)
        db.flush()
    else:
        guest.name = guest.name or "王退测"

    room = db.query(Room).filter(Room.hotel_id == hotel_id).order_by(Room.id.asc()).first()
    today = date.today()
    now = datetime.now()

    def _mk_order(order_no: str, status: str, total: float) -> Order:
        o = Order(
            hotel_id=hotel_id,
            order_no=order_no,
            guest_id=guest.id,
            one_id=guest.one_id,
            guest_phone=REFUND_CASE_PHONE,
            check_in=today - timedelta(days=2),
            check_out=today + timedelta(days=1),
            nights=3,
            rooms=1,
            adults=1,
            total_amount=Decimal(str(total)),
            status=status,
            payment_status="paid",
            note="refund_case_seed",
        )
        db.add(o)
        db.flush()
        return o

    def _mk_checkin(o: Order, room_no: str) -> PmsCheckin:
        ck = PmsCheckin(
            hotel_id=hotel_id,
            order_id=o.id,
            room_id=room.id if room else None,
            guest_id=guest.id,
            guest_name=guest.name,
            status="inhouse" if o.status == "checked_in" else "checked_out",
            room_no=room_no,
            actual_checkin_at=now - timedelta(days=2),
        )
        db.add(ck)
        db.flush()
        return ck

    def _mk_folio(
        o: Order,
        ck: PmsCheckin,
        charges: list[tuple[str, str, float]],
        payment_total: float,
        *,
        refunds: list[tuple[str, float]] | None = None,
    ) -> PmsFolio:
        folio = PmsFolio(
            hotel_id=hotel_id,
            folio_no=f"FL-{o.order_no}",
            order_id=o.id,
            checkin_id=ck.id,
            guest_id=guest.id,
            status="open" if o.status == "checked_in" else "closed",
            charge_total=Decimal(str(sum(c[2] for c in charges))),
            payment_total=Decimal(str(payment_total)),
            balance=Decimal("0"),
        )
        db.add(folio)
        db.flush()
        for et, desc, amt in charges:
            db.add(
                PmsFolioEntry(
                    folio_id=folio.id,
                    entry_type=et,
                    biz_date=today - timedelta(days=1),
                    description=desc,
                    amount=Decimal(str(amt)),
                    source="refund_case_seed",
                )
            )
        for desc, amt in refunds or []:
            db.add(
                PmsFolioEntry(
                    folio_id=folio.id,
                    entry_type="refund",
                    biz_date=today,
                    description=desc,
                    amount=Decimal(str(-abs(amt))),
                    source="refund_case_seed",
                )
            )
        return folio

    def _mk_pay(o: Order, folio: PmsFolio, method: str, amount: float, slip: str) -> Payment:
        p = Payment(
            hotel_id=hotel_id,
            order_id=o.id,
            folio_id=folio.id,
            method=method,
            amount=Decimal(str(amount)),
            received_amount=Decimal(str(amount)),
            pos_slip_no=slip,
            settle_type="full",
            note="refund_case_seed",
            paid_at=now - timedelta(days=1),
        )
        db.add(p)
        db.flush()
        return p

    # A：微信原路可退（主路径）
    o_wx = _mk_order(REFUND_CASE_ORDERS["wx"], "checked_in", 1004)
    ck_wx = _mk_checkin(o_wx, REFUND_CASE_ROOM)
    fl_wx = _mk_folio(
        o_wx,
        ck_wx,
        [
            ("room", "第 2 晚房费", 428),
            ("fnb", "早餐", 76),
            ("deposit", "押金", 500),
        ],
        payment_total=1004,
    )
    _mk_pay(o_wx, fl_wx, "wechat_pos", 1004, "WX20260831RF001")

    # A：支付宝原路可退（边角订单号）
    o_ali = _mk_order(REFUND_CASE_ORDERS["ali"], "checked_out", 688)
    ck_ali = _mk_checkin(o_ali, "RF8802")
    fl_ali = _mk_folio(
        o_ali,
        ck_ali,
        [("room", "房费合计", 688)],
        payment_total=688,
    )
    _mk_pay(o_ali, fl_ali, "alipay_pos", 688, "ALI20260831RF002")

    # 过滤：已全额退
    o_full = _mk_order(REFUND_CASE_ORDERS["full"], "checked_out", 500)
    ck_full = _mk_checkin(o_full, "RF8803")
    fl_full = _mk_folio(
        o_full,
        ck_full,
        [("room", "房费", 500)],
        payment_total=500,
        refunds=[("已全额退回", 500)],
    )
    _mk_pay(o_full, fl_full, "wechat_pos", 500, "WX20260831RF003")

    # 过滤：已取消
    _mk_order(REFUND_CASE_ORDERS["cancel"], "cancelled", 300)

    _link_refund_case_ticket(db, hotel_id, o_wx.id)
    db.commit()
    return {
        "skipped": False,
        "guest_id": guest.id,
        "phone": REFUND_CASE_PHONE,
        "room": REFUND_CASE_ROOM,
        "order_wx": o_wx.id,
        "order_ali": o_ali.id,
        "orders": list(REFUND_CASE_ORDERS.values()),
    }


def _link_refund_case_ticket(db: Session, hotel_id: int, order_id: int) -> None:
    """方案 C：待办退款工单绑定真实 order_id，便于一点载入。"""
    t = (
        db.query(RefundAdjustTicket)
        .filter(
            RefundAdjustTicket.hotel_id == hotel_id,
            RefundAdjustTicket.ticket_no == "RA-REF-8821",
        )
        .first()
    )
    if t:
        t.order_id = order_id
        t.order_no = REFUND_CASE_ORDERS["wx"]
        t.guest_name_masked = seed_text("王**", "W**")
        t.detail = seed_text(
            f"取消 1 晚，退 ¥428 · 绑定 {REFUND_CASE_ORDERS['wx']}",
            f"Cancel 1 night, refund ¥428 · linked {REFUND_CASE_ORDERS['wx']}",
        )
        t.updated_at = datetime.now()
        return
    now = datetime.now()
    t = RefundAdjustTicket(
        ticket_no="RA-REF-CASE",
        hotel_id=hotel_id,
        op_type="refund",
        status="pending_approval",
        title=seed_text(
            f"部分退款 · {REFUND_CASE_ORDERS['wx']}",
            f"Partial refund · {REFUND_CASE_ORDERS['wx']}",
        ),
        detail=seed_text("待办退款 · 点入可定位源单", "Pending refund · open to locate source order"),
        order_id=order_id,
        order_no=REFUND_CASE_ORDERS["wx"],
        guest_name_masked=seed_text("王**", "W**"),
        amount_cents=42800,
        reason=seed_text("客人要求取消第 2 晚", "Guest asked to cancel night 2"),
        refund_method="original_wechat",
        applicant_id="demo",
        created_at=now,
        updated_at=now,
    )
    db.add(t)
    db.flush()
    db.add(
        RefundAdjustAudit(
            hotel_id=hotel_id,
            ticket_id=t.id,
            event="SEED",
            actor_id="system",
            memo=seed_text("退款待办工单", "Refund pending ticket"),
        )
    )
