# SPDX-License-Identifier: Apache-2.0
"""guest_aliases 表：客人其他名字。"""

from __future__ import annotations

from sqlalchemy import inspect, text


def ensure_guest_aliases_schema(engine) -> None:
    insp = inspect(engine)
    if insp.has_table("guests"):
        cols = {c["name"] for c in insp.get_columns("guests")}
        if "merged_into_guest_id" not in cols:
            with engine.begin() as conn:
                conn.execute(
                    text(
                        "ALTER TABLE guests ADD COLUMN merged_into_guest_id INTEGER REFERENCES guests(id) ON DELETE SET NULL"
                    )
                )
    if insp.has_table("guest_aliases"):
        return
    with engine.begin() as conn:
        conn.execute(
            text("""
            CREATE TABLE guest_aliases (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                guest_id INTEGER NOT NULL REFERENCES guests(id) ON DELETE CASCADE,
                alias_name VARCHAR(80) NOT NULL,
                source VARCHAR(40) DEFAULT 'merge',
                merged_from_guest_id INTEGER,
                note VARCHAR(200),
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                UNIQUE(guest_id, alias_name)
            )
        """)
        )
        conn.execute(text("CREATE INDEX IF NOT EXISTS ix_guest_aliases_guest ON guest_aliases(guest_id)"))
