-- SPDX-License-Identifier: Apache-2.0
-- 权限目录（与 src/infra/rbac_catalog.py 对齐）
INSERT INTO permissions (code, name, kind, module, sort_order) VALUES
    ('menu.overview.dashboard', '经营看板', 'menu', 'overview', 10),
    ('menu.overview.pricing', '价格助手', 'menu', 'overview', 20),
    ('menu.overview.forecast', '营收预测', 'menu', 'overview', 30),
    ('menu.orders.center', '订单中心', 'menu', 'orders', 10),
    ('menu.orders.booking', '前台预订', 'menu', 'orders', 20),
    ('menu.orders.assign', '待分房', 'menu', 'orders', 30),
    ('menu.orders.checkout', '收银退房', 'menu', 'orders', 40),
    ('menu.rooms.board', '房态看板', 'menu', 'rooms', 10),
    ('menu.rooms.hk', '房务任务', 'menu', 'rooms', 20),
    ('menu.rooms.inventory', '库存预售', 'menu', 'rooms', 30),
    ('menu.rooms.assets', '设备设施', 'menu', 'rooms', 40),
    ('menu.rooms.hk_reports', '房务报表', 'menu', 'rooms', 50),
    ('menu.crm.directory', '全景列表', 'menu', 'crm', 10),
    ('menu.crm.cohort', '客群运营', 'menu', 'crm', 20),
    ('menu.crm.oneid', 'OneID归并', 'menu', 'crm', 30),
    ('menu.crm.vip', 'VIP管家', 'menu', 'crm', 40),
    ('menu.crm.tags', '标签管理', 'menu', 'crm', 50),
    ('menu.analytics.insights', '专题洞察', 'menu', 'analytics', 10),
    ('menu.analytics.profit', '利润优化', 'menu', 'analytics', 20),
    ('menu.analytics.ai', 'AI问数', 'menu', 'analytics', 30),
    ('menu.finance.deposit', '押金管理', 'menu', 'finance', 10),
    ('menu.finance.refund', '退改与反结账', 'menu', 'finance', 20),
    ('menu.finance.shift', '交班接班', 'menu', 'finance', 30),
    ('menu.finance.night_audit', '夜间审计', 'menu', 'finance', 40),
    ('menu.finance.recon', '财务对账', 'menu', 'finance', 50),
    ('menu.finance.invoice', '发票管理', 'menu', 'finance', 60),
    ('menu.finance.ar_ap', '应收应付', 'menu', 'finance', 70),
    ('menu.finance.reports', '财务报表', 'menu', 'finance', 80),
    ('menu.mkt.overview', '私域总览', 'menu', 'mkt', 10),
    ('menu.mkt.coupons', '优惠券中心', 'menu', 'mkt', 20),
    ('menu.mkt.landing', '页面装修器', 'menu', 'mkt', 30),
    ('menu.mkt.members', '会员体系', 'menu', 'mkt', 40),
    ('menu.mkt.points', '积分规则', 'menu', 'mkt', 50),
    ('menu.system.wecom', '企业微信接入', 'menu', 'system', 10),
    ('menu.system.llm', '大语言模型', 'menu', 'system', 20),
    ('menu.system.map', '地图配置', 'menu', 'system', 25),
    ('menu.system.finance_params', '财务参数', 'menu', 'system', 30),
    ('menu.system.room_types', '房型管理', 'menu', 'system', 40),
    ('menu.system.room_master', '房间档案', 'menu', 'system', 50),
    ('menu.system.users', '用户与账号', 'menu', 'system', 60),
    ('menu.system.rbac', '角色权限', 'menu', 'system', 70),
    ('action.orders.write', '订单订住退分房', 'action', 'orders', 10),
    ('action.rooms.status', '房态日常改态', 'action', 'rooms', 10),
    ('action.rooms.lock_ooo_price', '锁房/OOO/改价', 'action', 'rooms', 20),
    ('action.rooms.master_write', '房间/房型改删', 'action', 'rooms', 30),
    ('action.hk.dispatch', '房务派工排班', 'action', 'rooms', 40),
    ('action.pricing.accept', '价格建议采纳', 'action', 'overview', 10),
    ('action.finance.night_audit', '夜审执行', 'action', 'finance', 10),
    ('action.finance.refund', '退款/反结账', 'action', 'finance', 20),
    ('action.mkt.coupon_grant', '发券/活动审批', 'action', 'mkt', 10),
    ('action.pii.reveal', '证件揭示/问数PII', 'action', 'crm', 10),
    ('action.system.users', '用户管理', 'action', 'system', 10),
    ('action.system.rbac', '角色权限配置', 'action', 'system', 20),
    ('action.system.map', '地图配置保存', 'action', 'system', 30)
ON CONFLICT (code) DO UPDATE
SET
    name = EXCLUDED.name,
    kind = EXCLUDED.kind,
    module = EXCLUDED.module,
    sort_order = EXCLUDED.sort_order;
